CREATE TABLE [dbo].[staging_auditcomply]
(
[name] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[id] [int] NULL,
[status] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[additional_signature_print] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[additional_signature_position] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[signature] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[asset_id] [int] NULL,
[asset_name] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[updated_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[close_audit_enabled] [bit] NULL,
[latitude] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[signature_position] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[report] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[closed_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[closed_notes] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[closed_by_signature] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[status_color] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[completed_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[closed_by_id] [int] NULL,
[created_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[state] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[longitude] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[signature_print] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[additional_signature] [bit] NULL,
[compliant] [bit] NULL,
[status_changed_on_close] [bit] NULL,
[device] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[published] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[auditor_id] [int] NULL,
[notes] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[observations] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[customresponses] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[nonconformance] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[question_id] [int] NULL,
[question_text] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[requirement_identifier] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[nonconformances] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[custom_responses] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[observation] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[recommendation] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[responses] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[observation_start_time] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[observation_end_time] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[custom_dropdown] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[custom_option_id] [int] NULL,
[field_label] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[field_value] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[nonconformance_id] [int] NULL,
[noncon_status] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[overdue] [bit] NULL,
[non_conformance] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[complete_by] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[approved_date] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[noncon_created_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[assigned_to] [int] NULL,
[assigned_by] [int] NULL,
[approved_by] [int] NULL
) ON [PRIMARY]
GO
