CREATE TABLE [dbo].[audit_header]
(
[name] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[id] [int] NULL,
[status] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[additional_signature_print] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[additional_signature_position] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[signature] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[asset_id] [int] NULL,
[asset_name] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[updated_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[close_audit_enabled] [bit] NULL,
[latitude] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[signature_position] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[report] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[closed_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[closed_notes] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[closed_by_signature] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[status_color] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[completed_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[closed_by_id] [int] NULL,
[created_at] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[state] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[longitude] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[signature_print] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[additional_signature] [bit] NULL,
[compliant] [bit] NULL,
[status_changed_on_close] [bit] NULL,
[device] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[published] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[auditor_id] [int] NULL,
[notes] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[audit_result] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
