SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[merge_auditcomply_header]
AS
MERGE dbo.audit_header AS target
USING (
		SELECT	DISTINCT 	
            staging_auditcomply.name,
            staging_auditcomply.id,
            staging_auditcomply.status,
            staging_auditcomply.additional_signature_print,
            staging_auditcomply.additional_signature_position,
            staging_auditcomply.signature,
            staging_auditcomply.asset_id,
            staging_auditcomply.asset_name,
            staging_auditcomply.updated_at,
            staging_auditcomply.close_audit_enabled,
            staging_auditcomply.latitude,
            staging_auditcomply.signature_position,
            staging_auditcomply.report,
            staging_auditcomply.closed_at,
            staging_auditcomply.closed_notes,
            staging_auditcomply.closed_by_signature,
            staging_auditcomply.status_color,
            staging_auditcomply.completed_at,
            staging_auditcomply.closed_by_id,
            staging_auditcomply.created_at,
            staging_auditcomply.state,
            staging_auditcomply.longitude,
            staging_auditcomply.signature_print,
            staging_auditcomply.additional_signature,
            staging_auditcomply.compliant,
            staging_auditcomply.status_changed_on_close,
            staging_auditcomply.device,
            staging_auditcomply.published,
            staging_auditcomply.auditor_id,
            staging_auditcomply.notes,
			dbo.staging_auditcomply.audit_result

FROM dbo.staging_auditcomply
) AS source

ON (target.id=source.id )
 WHEN NOT MATCHED BY TARGET THEN 
 INSERT (name,
            id,
            status,
            additional_signature_print,
            additional_signature_position,
            signature,
            asset_id,
            asset_name,
            updated_at,
            close_audit_enabled,
            latitude,
            signature_position,
            report,
            closed_at,
            closed_notes,
            closed_by_signature,
            status_color,
            completed_at,
            closed_by_id,
            created_at,
            state,
            longitude,
            signature_print,
            additional_signature,
            compliant,
            status_changed_on_close,
            device,
            published,
            auditor_id,
            notes,
			audit_result
)
 VALUES (name,
            id,
            status,
            additional_signature_print,
            additional_signature_position,
            signature,
            asset_id,
            asset_name,
            updated_at,
            close_audit_enabled,
            latitude,
            signature_position,
            report,
            closed_at,
            closed_notes,
            closed_by_signature,
            status_color,
            completed_at,
            closed_by_id,
            created_at,
            state,
            longitude,
            signature_print,
            additional_signature,
            compliant,
            status_changed_on_close,
            device,
            published,
            auditor_id,
            notes,
			audit_result
			)
			WHEN MATCHED THEN UPDATE SET 
			name = source.name,
            status = source.status,
            additional_signature_print = source.additional_signature_print,
            additional_signature_position = source.additional_signature_position,
            signature = source.SIGNATURE,
            asset_id = source.asset_id,
            asset_name = source.asset_name,
            updated_at = source.updated_at,
            close_audit_enabled = source.close_audit_enabled,
            latitude = source.latitude,
            signature_position = source.signature_position,
            report = source.report,
            closed_at = source.closed_at,
            closed_notes = source.closed_notes,
            closed_by_signature = source.closed_by_signature,
            status_color = source.status_color,
            completed_at = source.completed_at,
            closed_by_id = source.closed_by_id,
            created_at = source.created_at,
            state = source.STATE,
            longitude = source.longitude,
            signature_print = source.signature_print,
            additional_signature = source.additional_signature,
            compliant = source.compliant,
            status_changed_on_close = source.status_changed_on_close,
            device = source.device,
            published = source.published,
            auditor_id = source.auditor_id,
            notes = source.notes,
			audit_result = source.audit_result
			;
GO
