SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE VIEW [dbo].[vis_view_dim_detail_property]
AS 

SELECT [dim_detail_property_key]
--      ,[source_system_id]
--      ,[client_code]
--      ,[matter_number]
--      ,[completion_date]
--      ,[date_if_fixed_1]
--      ,[date_if_fixed_2]
--      ,[date_if_fixed_3]
--      ,[date_if_fixed_4]
      ,[date_of_lease]
--      ,[date_prepare_sale_contract_completed]
--      ,[earliest_break_date_if_rolling]
--      ,[expiry_of_section_25_notice]
--      ,[expiry_of_section_26_notice]
--      ,[insurance_dates]
--      ,[activity_code]
--      ,[additional_break_notes]
      ,[address]
      ,[agent]
--      ,[alert_auditor]
      ,[be_name]
      ,[be_number]
--      ,[bibby_contact]
--      ,[bibbys_landlord]
--      ,[bibbys_landlord_agent]
      ,[key_date_name]
--      ,[l_notice_period_1]
--      ,[l_notice_period_2]
--      ,[l_notice_period_3]
--      ,[l_penalty_rental_period_1]
--      ,[l_penalty_rental_period_2]
--      ,[l_penalty_rental_period_3]
      ,[next_key_date]
--      ,[next_key_date_action]
--      ,[next_key_date_action2]
--      ,[notice_period_a]
--      ,[notice_period_b]
--      ,[notice_period_c]
--      ,[bibbys_landlord_agents_address]
--      ,[bibbys_tenant]
--      ,[bibbys_tenant_contact_details]
--      ,[break_1]
      ,[break_clause_notice_required]
--      ,[bruntwood_case_status]
--      ,[budget_code]
      ,[case_classification]
--      ,[case_classification_code]
--      ,[case_type]
--      ,[case_type_pol]
--      ,[case_type_rmg]
--      ,[cg_legal_services_file_number]
--      ,[city]
--      ,[claim_from_bibbys_landlord]
--      ,[client]
--      ,[client_case_reference]
--      ,[client_contact]
--      ,[client_listing_code]
--      ,[client_report]
--      ,[comments]
--      ,[company_reference]
--      ,[complexity]
--      ,[coop_purchase_order_1]
--      ,[coop_purchase_order_10]
--      ,[coop_purchase_order_11]
--      ,[coop_purchase_order_12]
--      ,[coop_purchase_order_13]
--      ,[coop_purchase_order_14]
--      ,[coop_purchase_order_15]
--      ,[coop_purchase_order_2]
--      ,[coop_purchase_order_3]
--      ,[coop_purchase_order_4]
--      ,[coop_purchase_order_5]
--      ,[coop_purchase_order_6]
--      ,[coop_purchase_order_7]
--      ,[coop_purchase_order_8]
--      ,[coop_purchase_order_9]
--      ,[court_application_made]
--      ,[current_situation]
--      ,[deeds_held]
--      ,[demised_premises]
--      ,[dependent_on_event]
--      ,[documents_under_negotiation_01]
--      ,[documents_under_negotiation_02]
--      ,[documents_under_negotiation_03]
--      ,[documents_under_negotiation_04]
--      ,[documents_under_negotiation_05]
--      ,[documents_under_negotiation_06]
--      ,[documents_under_negotiation_07]
--      ,[documents_under_negotiation_08]
--      ,[documents_under_negotiation_09]
--      ,[documents_under_negotiation_10]
      ,[estate_manager]
      ,[external_surveyor]
      ,[fixed_feehourly_rate]
--      ,[gl_code]
--      ,[group_company]
--      ,[hk_approval]
--      ,[hostile_notice]
--      ,[how_many_american_searches_were_completed]
--      ,[how_many_european_searches_were_completed]
--      ,[how_many_individual_searches_were_required]
--      ,[how_many_rest_of_world_searches_were_completed]
--      ,[how_many_uk_company_searches_were_completed]
--      ,[incentives]
      ,[insurance_premium]
      ,[landlord]
      ,[landlord_address]
--      ,[landlords_break_option]
--      ,[legal_contact]
--      ,[main_operator_customer]
--      ,[matter]
--      ,[network_code]
--      ,[next_action]
--      ,[penalty_if_exercised]
--      ,[penalty_sum]
--      ,[personal_to_landlord]
--      ,[personal_to_tenant]
      ,[postcode]
--      ,[present_position]
--      ,[priority]
      ,[property_address]
--      ,[property_address_1]
--      ,[property_address_2]
--      ,[property_contact]
      ,[property_ref]
--      ,[pspurchaser_1_full_name]
--      ,[pspurchaser_2_full_name]
--      ,[pspurchaser_3_full_name]
--      ,[pspurchaser_4_full_name]
--      ,[purchase_order_number]
      ,[rateable_value]
      ,[rates_payable]
      ,[rates_payable_to]
--      ,[rent_free_period_if_not_exercised]
--      ,[repairing_liability]
--      ,[rolling_or_fixed_date]
--      ,[search_area]
--      ,[service_charge_payable_to]
--      ,[signed_deed_of_assignment]
--      ,[status]
--      ,[store_name]
--      ,[store_number]
--      ,[surveyor_dealing]
--      ,[tenants_break_option]
--      ,[transaction_1]
--      ,[type_of_matter]
--      ,[was_there_a_company_search_fee]
--      ,[was_there_an_individual_search_fee]
--      ,[weightmans_po_reference]
--      ,[will_a_third_party_pay_our_bills]
--      ,[last_date_for_court_application]
--      ,[latest_break_date_if_rolling]
      ,[lease_end_date]
--      ,[lease_expired]
      ,[lease_expiry_date]
      ,[lease_start_date]
      ,[rent_commencement_date]
      ,[rent_review_dates]
--      ,[s25_notice_date]
--      ,[s26_notice_date]
--      ,[search_date]
--      ,[two_months_from_service_of_valid_section_26_notice]
--      ,[coop_po_reference]
--      ,[case_type_asw]
--      ,[documents_under_negotiation]
--      ,[outcome_of_investigation_detail]
--      ,[reference]
--      ,[status_asw]
--      ,[tab_on_property_schedule]
--      ,[term]
--      ,[dss_create_time]
--      ,[dss_update_time]
--      ,[action_date]
--      ,[actual_break_date]
--      ,[actual_completion_date]
--      ,[actual_exchange_date]
--      ,[anticipated_completion_date]
--      ,[anticipated_exchange_date]
      ,[break_date]
--      ,[by_when]
--      ,[date_coa_complete_can_be_actioned]
--      ,[date_coa_received]
--      ,[date_documents_sent_out]
--      ,[date_of_ecn]
--      ,[date_pack_sent_out]
--      ,[date_received_by_solicitors]
--      ,[date_sent_to_partner]
      ,[first_rent_review]
      ,[fourth_rent_review]
--      ,[lease_commencement_date]
--      ,[lease_date]
--      ,[punch_aborted_date]
--      ,[punch_completion_date]
--      ,[punch_peat]
--      ,[agreement_type]
--      ,[any_documents_affecting]
--      ,[application_name]
--      ,[application_reason]
--      ,[application_type]
--      ,[approval]
--      ,[asset_manager]
--      ,[board_approval]
--      ,[brm_name]
--      ,[by_whom]
--      ,[capital_contribution]
--      ,[coa_complete]
--      ,[company]
--      ,[country]
--      ,[currency]
--      ,[current_tenant]
--      ,[date_lease_sent_to_romans]
--      ,[deadline_for_submitting_planning_application]
--      ,[deadline_responsibility_for_premises_license_application]
--      ,[deposit_collection_method]
--      ,[deposit_funds_cleared]
--      ,[details_of_other_conditions]
--      ,[developer]
--      ,[estimated_construction_period]
--      ,[exemption_and_approval]
--      ,[first_payment_received_and_cleared]
--      ,[foundation_week_training_attended]
--      ,[foundation_week_training_waivered]
--      ,[guarantor]
--      ,[information_or_documents_awaited_complete_coa]
--      ,[instruction]
--      ,[l_ta_protected]
--      ,[lease_or_break_or_clause]
--      ,[lease_type]
--      ,[letter_of_engagment_waivered]
--      ,[linked_transaction]
--      ,[location]
--      ,[longstop_date_for_completion]
--      ,[longstop_date_for_satisfying_conditions]
--      ,[machine_games_duty_registration_number_supplied]
--      ,[om]
--      ,[outstanding_issues_or_comments]
--      ,[pdm]
      ,[pentland_brand_contact]
      ,[pentland_reference]
--      ,[personal_licence_issuing_auth]
--      ,[personal_licence_number]
--      ,[professional_advice_loa]
--      ,[professional_advice_loa_waivered]
--      ,[property_name_]
--      ,[punch_area_code]
--      ,[punch_cop]
--      ,[punch_edm]
--      ,[punch_inv]
--      ,[punch_lease_or_renewal]
--      ,[punch_loa]
--      ,[punch_matter_status]
--      ,[punch_owning_company]
--      ,[punch_regional_valuation_surveyor]
--      ,[punch_rvm]
--      ,[punch_sow]
--      ,[purchaser_name]
--      ,[rag]
--      ,[repair_obligations]
--      ,[rom_name]
--      ,[rvs]
--      ,[sale_of_part_or_whole]
--      ,[sales_contract_or_purchasing_outright]
--      ,[spirit]
--      ,[stage]
--      ,[status_of_coa]
--      ,[team]
--      ,[tenant]
      ,[tenant_name]
      ,[tenure]
--      ,[town]
--      ,[traffic_light]
--      ,[trustee_approval]
--      ,[type_of_let]
--      ,[punch_renewal_date]
--      ,[received_signed_from_partner]
--      ,[received_signed_from_punch]
      ,[second_rent_review]
--      ,[solicitor_estimated_date_completion]
--      ,[submission_date]
      ,[third_rent_review]
--      ,[turnover_statement_expiry]
--      ,[application_local_authority]
--      ,[punch_gk_term_years]
--      ,[region_code]
--      ,[end_date]
--      ,[exchange_date]
      ,[fifth_rent_review]
--      ,[final_notice_served]
--      ,[first_notice_served]
      ,[landlord_break_date]
--      ,[settled]
--      ,[start]
--      ,[additional_info_re__major_works]
--      ,[area]
--      ,[branch]
--      ,[branch_code]
--      ,[brand]
      ,[campus]
--      ,[capital_contribution_received]
--      ,[car_parking]
--      ,[cg_legal_services_contact]
--      ,[commercial_bl_status]
      ,[date_of_transfer]
--      ,[dp_location]
--      ,[dp_number]
--      ,[emls_work_category]
--      ,[enfield_case_status]
--      ,[enfield_next_action]
--      ,[file_type]
      ,[freehold_leasehold]
--      ,[freeholder_if_applicable]
--      ,[hsbc_charge]
--      ,[landlord_rolling_break_notice]
--      ,[latitude]
--      ,[lease_id]
      ,[lease_term]
--      ,[licence_to_occupy]
--      ,[lmh_current_position]
--      ,[longitude]
--      ,[m3_code]
--      ,[management_company]
--      ,[miscellaneous_issues]
      ,[mortgage_offer_received]
--      ,[mortgages]
--      ,[op_co]
      ,[option_to_break]
      ,[option_to_purchase]
--      ,[option_to_renew]
--      ,[payable]
--      ,[protected]
--      ,[received_proposed_completion_date__docs]
--      ,[region]
      ,[registered_proprietor]
--      ,[reservation_status]
--      ,[responsibilty_budget]
      ,[restrictions_on_register]
--      ,[review_pattern]
--      ,[rexel_reference]
--      ,[scanned]
      ,[service_charges]
      ,[starting_rent]
--      ,[tenant_rolling_break_notice]
      ,[title_number]
--      ,[university_lead]
--      ,[upcoming_works]
--      ,[vat]
--      ,[vendor]
--      ,[years_left_on_lease]
--      ,[target_completion_date]
      ,[tenant_break]
      ,[term_end_date]
      ,[term_start_date]
--      ,[updated]
--      ,[property_type_1]
--      ,[property_type_2]
--      ,[case_type_property_1]
--      ,[case_type_property_2]
--      ,[case_type_property_3]
--      ,[completed_count]
--      ,[fixed_fee_hourly_rate]
--      ,[company_reference_no]
--      ,[property_address_desc]
--      ,[present_position_desc]
--      ,[fixed_fee_hourly_rate_property]
--      ,[number_working_days_progress]
--      ,[pol_case_officer]
--      ,[purchaser_contact_details]
--      ,[rent_statment_received_count]
--      ,[present_position_pr]
--      ,[status_rm]
--      ,[target_date]
--      ,[date_elements_agreed]
--      ,[case_type_asw_desc]
--      ,[property_case_type]
--      ,[property_client_contact]
--      ,[date_documents_received_assignor_solicitors]
--      ,[date_landlord_solicitor_documents_received]
--      ,[date_required_documents_received]
--      ,[date_seller_solicitor_documents_received]
--      ,[status_rm_date]
--      ,[case_status]
--      ,[purchase_order_number_additional]
--      ,[court_hearing_date]
--      ,[other_key_dates]
--      ,[status_comment]
--      ,[clarion_housing_display]
--      ,[status_history]
--      ,[address_property]
--      ,[contact_property]
--      ,[exclude_from_dashboard]
--      ,[fascia]
--      ,[proposed_completion_date]
--      ,[proposed_rent]
--      ,[next_review_date]
--      ,[lta_1954]
--      ,[term_end_date_rmg]
--      ,[case_type_rmg_desc]
--      ,[date_of_entry]
--      ,[date_of_registration]
--      ,[date_sub_lease_end]
--      ,[date_sub_lease_start]
--      ,[property_type_3]
--      ,[rent_review_frequency]
--      ,[petrol_brand]
--      ,[extended]
--      ,[assignation]
  FROM [red_dw].[dbo].[dim_detail_property] WITH (NOLOCK)


GO
