SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE VIEW [dbo].[vis_view_dim_client_involvement]
AS 

SELECT [dim_client_involvement_key]
--      ,[client_code]
--      ,[matter_number]
--      ,[acm_1_key]
--      ,[broker_1_key]
--      ,[broker_2_key]
--      ,[broker_3_key]
--      ,[broker_4_key]
--      ,[buyer_1_key]
--      ,[buyersellers_1_key]
--      ,[client_1_key]
--      ,[clientcontact_2_key]
--      ,[clientcontact_1_key]
--      ,[clientcontact_4_key]
--      ,[clientcontact_3_key]
--      ,[clientemployer_1_key]
--      ,[clientorganisa_1_key]
--      ,[clientstatent_1_key]
--      ,[coopemailadd_1_key]
--      ,[coopemailauth_1_key]
--      ,[depotmanager_1_key]
--      ,[depotmanager_2_key]
--      ,[emprelmanager_1_key]
--      ,[fraudteam_1_key]
--      ,[hopod_1_key]
--      ,[hopod_2_key]
--      ,[insuredbroker_2_key]
--      ,[insuredbroker_1_key]
--      ,[insuredclient_2_key]
--      ,[insuredclient_1_key]
--      ,[insuredclient_3_key]
--      ,[insuredclient_4_key]
--      ,[insurerclient_4_key]
--      ,[insurerclient_3_key]
--      ,[insurerclient_2_key]
--      ,[insurerclient_1_key]
--      ,[misc_2_key]
--      ,[misc_1_key]
--      ,[misc_3_key]
--      ,[misc_4_key]
--      ,[mmiemailadmin_4_key]
--      ,[mmiemailadmin_3_key]
--      ,[mmiemailadmin_2_key]
--      ,[mmiemailadmin_1_key]
--      ,[ostescalation_1_key]
--      ,[owner_1_key]
--      ,[persname_1_key]
--      ,[personnel_1_key]
--      ,[poda_1_key]
--      ,[poda_2_key]
--      ,[propertycontact_1_key]
--      ,[psc_1_key]
--      ,[psc_2_key]
--      ,[purchaser_3_key]
--      ,[purchaser_4_key]
--      ,[purchaser_1_key]
--      ,[purchaser_2_key]
--      ,[purchasersols_1_key]
--      ,[purchasersols_4_key]
--      ,[purchasersols_3_key]
--      ,[purchasersols_2_key]
--      ,[rmgemailauth_1_key]
--      ,[rmgupdates_1_key]
--      ,[tsm_1_key]
--      ,[tsm_2_key]
--      ,[uapprovedost_1_key]
--      ,[zinstructions_1_key]
--      ,[zinstructions_2_key]
--      ,[zinstructions_3_key]
--      ,[zinstructions_4_key]
--      ,[zurapportbills_2_key]
--      ,[zurapportbills_1_key]
--      ,[zurichinsured_1_key]
--      ,[dss_update_time]
--      ,[acm_name]
--      ,[broker_name]
--      ,[buyer_name]
--      ,[buyersellers_name]
--      ,[client_name]
--      ,[clientcontact_name]
--      ,[clientemployer_name]
--      ,[clientorganisa_name]
--      ,[clientstatent_name]
--      ,[coopemailadd_name]
--      ,[coopemailauth_name]
--      ,[depotmanager_name]
--      ,[emprelmanager_name]
--      ,[fraudteam_name]
--      ,[hopod_name]
--      ,[insuredbroker_name]
      ,[insuredclient_name]
      ,[insurerclient_name]
--      ,[misc_name]
--      ,[mmiemailadmin_name]
--      ,[ostescalation_name]
--      ,[owner_name]
--      ,[persname_name]
--      ,[personnel_name]
--      ,[poda_name]
--      ,[propertycontact_name]
--      ,[psc_name]
--      ,[purchaser_name]
--      ,[purchasersols_name]
--      ,[rmgemailauth_name]
--      ,[rmgupdates_name]
--      ,[tsm_name]
--      ,[uapprovedost_name]
--      ,[zinstructions_name]
--      ,[zurapportbills_name]
--      ,[zurichinsured_name]
--      ,[acm_reference]
--      ,[broker_reference]
--      ,[buyer_reference]
--      ,[buyersellers_reference]
--      ,[client_reference]
--      ,[clientcontact_reference]
--      ,[clientemployer_reference]
--      ,[clientorganisa_reference]
--      ,[clientstatent_reference]
--      ,[coopemailadd_reference]
--      ,[coopemailauth_reference]
--      ,[depotmanager_reference]
--      ,[emprelmanager_reference]
--      ,[fraudteam_reference]
--      ,[hopod_reference]
--      ,[insuredbroker_reference]
      ,[insuredclient_reference]
      ,[insurerclient_reference]
--      ,[misc_reference]
--      ,[mmiemailadmin_reference]
--      ,[ostescalation_reference]
--      ,[owner_reference]
--      ,[persname_reference]
--      ,[personnel_reference]
--      ,[poda_reference]
--      ,[propertycontact_reference]
--      ,[psc_reference]
--      ,[purchaser_reference]
--      ,[purchasersols_reference]
--      ,[rmgemailauth_reference]
--      ,[rmgupdates_reference]
--      ,[tsm_reference]
--      ,[uapprovedost_reference]
--      ,[zinstructions_reference]
--      ,[zurapportbills_reference]
--      ,[zurichinsured_reference]
  FROM [red_dw].[dbo].[dim_client_involvement] WITH (NOLOCK)


GO
