SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE VIEW [dbo].[vis_view_dim_detail_outcome]
AS 
SELECT 
[dim_detail_outcome_key]
--      ,[source_system_id]
--      ,[client_code]
--      ,[matter_number]
--      ,[aig_has_there_been_a_mediation]
--      ,[aig_outcome_of_instruction]
--      ,[aig_where_you_have_had_a_trial_were_you_successful]
--      ,[are_we_pursuing_a_recovery]
--      ,[capita_interim_payment_made]
--      ,[costs_outcome]
--      ,[disease_are_we_dealing_with_the_costs]
--      ,[global_settlement]
--      ,[grpageas_name_of_costs_negotiator]
--      ,[grpageas_reason_colossus_exceeded]
--      ,[liability_outcome]
--      ,[ll00_settlement_basis]
--      ,[ll28_provisional_damages_paid]
--      ,[percent_client_liability]
--      ,[claim_status]
--      ,[complaint_received]
--      ,[date_indemnity_settled]
--      ,[excluded]
--      ,[exclude_from_reports]
--      ,[filestatus_1]
--      ,[filestatus_2]
--      ,[lifecycle_of_claim]
--      ,[nmi114_flag]
--      ,[nmi126_wps048_coalesce]
--      ,[outcome]
--      ,[reason_for_success]
--      ,[repudiated]
--      ,[settled_without_hearing]
--      ,[status_historic]
--      ,[struckout]
--      ,[success_at_trial_1]
--      ,[tab2]
--      ,[local_gov_rmg_action_requiredlessons_learned]
--      ,[mib_fraud_settlement_basis]
--      ,[mib_grp_costs_negotiators_used]
--      ,[mib_name_of_costs_negotiators]
--      ,[mib_unit_total]
--      ,[capita_date_final_fee_paid]
      ,[date_claim_concluded]
--      ,[date_claimants_costs_received]
--      ,[coop_fraud_pav_payment_made]
--      ,[grpageas_percent_of_our_clients_liability]
--      ,[percent_estimate_of_reduction_for_litigation_risk]
--      ,[percent_of_contributory_negligence_agreed]
--      ,[percent_success_fee_claimed]
--      ,[percent_success_fee_paid]
--      ,[recovery_claimants_our_client_damages]
      ,[date_costs_settled]
--      ,[date_of_detailed_assessment]
--      ,[date_of_issue_of_n252_and_bill]
--      ,[date_of_issue_of_part_8_proceedings]
--      ,[date_of_provisional_assessment]
--      ,[date_of_tenth_interim_damages_payment]
--      ,[date_points_of_dispute_filed]
      ,[date_referral_to_costs_unit]
--      ,[grpageas_date_of_referral_to_costs_unit]
--      ,[mib_grp_zurich_pizza_hut_date_of_final_bill]
--      ,[sabre_admin_closure_date]
--      ,[zurich_result_date]
      ,[outcome_of_case]
--      ,[peel_ports_outcome]
--      ,[percent_of_contribution_from_other_insurers]
--      ,[police_was_this_a_jury_trial]
--      ,[qbe_exclude_from_report]
--      ,[settlement_on_litigation_risk_basis]
--      ,[zurich_recovery_does_the_claimant_have_a_cfa_indicator]
--      ,[zurich_result_method]
--      ,[dss_create_time]
--      ,[dss_update_time]
--      ,[liability_admitted]
--      ,[et_outcome_group]
--      ,[outcome_hr]
--      ,[final_bill_date_grp]
--      ,[groupama_outcome]
--      ,[outcome_of_instruction]
--      ,[grpageas_hourly_judgment]
--      ,[judgment_entered]
FROM red_dw.dbo.dim_detail_outcome WITH (NOLOCK)

WHERE LOWER(ISNULL(outcome_of_case,'')) <> 'exclude from reports'


GO
