SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE VIEW [dbo].[vis_view_fact_finance_summary]
AS 

SELECT   [master_fact_key]
--		,[source_system_id]
--      ,[client_code]
--      ,[matter_number]
--      ,[ate_premium_claimed]
--      ,[ate_premium_paid]
--      ,[claimants_costs_interims]
--      ,[claimants_costs_paid]
--      ,[claimants_solicitors_disbursements_paid]
--      ,[claimants_total_costs_paid_by_all_parties]
--      ,[commercial_costs_estimate_net]
      ,[costs_claimed_by_another_defendant]
--      ,[cru]
--      ,[cru_initial_reserve]
--      ,[cru_reserve]
--      ,[damages_interims]
      ,[damages_paid]
--      ,[damages_paid_to_date]
      ,[damages_reserve]
      ,[damages_reserve_initial]
--      ,[damages_reserve_net]
      ,[defence_costs_billed]
      ,[defence_costs_reserve]
      ,[defence_costs_reserve_initial]
--      ,[defence_costs_reserve_net]
      ,[detailed_assessment_costs_claimed_by_claimant]
      ,[detailed_assessment_costs_paid]
      ,[disbursements_billed]
      ,[fixed_fee_amount]
--      ,[indemnity_spend]
--      ,[indemnity_spend_net_recoveries]
--      ,[interlocutory_costs_paid_to_claimant]
--      ,[opponents_disbursements_paid]
      ,[other_defendants_costs_paid]
      ,[other_defendants_costs_reserve]
      ,[other_defendants_costs_reserve_initial]
--      ,[recovery_claimants_damages_via_third_party_contribution]
--      ,[recovery_defence_costs_via_third_party_contribution]
--      ,[recovery_defence_costs_from_claimant]
--      ,[percentage_total_savings_damages_and_costs]
--      ,[personal_injury_paid]
--      ,[special_damages_miscellaneous_paid]
--      ,[special_damages_miscellaneous_reserve]
      ,[total_amount_billed]
--      ,[total_costs_recovery]
--      ,[total_damages_and_tp_costs_reserve]
      ,[total_paid]
--      ,[total_paid_net_recoveries]
      ,[total_recovery]
      ,[total_reserve]
      ,[total_reserve_initial]
      ,[total_reserve_net]
--      ,[total_savings]
--      ,[total_savings_damages]
--      ,[total_savings_damages_and_costs]
--      ,[total_savings_net_recoveries]
      ,[total_settlement_value_of_the_claim_paid_by_all_the_parties]
      ,[total_tp_costs_paid]
--      ,[total_tp_costs_paid_to_date]
      ,[tp_costs_reserve]
      ,[tp_costs_reserve_initial]
--      ,[tp_costs_reserve_net]
--      ,[tp_total_costs_claimed]
      ,[total_costs_claimed]
      ,[total_costs_paid]
      ,[unpaid_disbursements]
      ,[vat_billed]
      ,[wip]
      ,[disbursement_balance]
--      ,[client_account_balance_of_matter]
--      ,[unpaid_bill_balance]
--      ,[deposit_account_balance]
--      ,[costs_to_date]
--      ,[dss_create_time]
--      ,[dss_update_time]
      ,[commercial_costs_estimate]
--      ,[costs_recovered_to_date]
--      ,[net_weightmans_costs_to_date]
--      ,[cru_nhs_paid]
--      ,[claimants_total_costs_claimed]
--      ,[amount_saved_on_reserve]
--      ,[total_case_costs_to_date]
--      ,[total_savings_percent]
--      ,[unbilled_time]
--      ,[time_billed]
--      ,[time_charge_value]
--      ,[paid_disbursements]
--      ,[defence_costs_billed_composite]
--      ,[total_billed_disbursements_vat]
--      ,[total_unbilled_disbursements_vat]
--      ,[defence_costs_vat]
--      ,[other_defendants_costs_reserve_net]
--      ,[portal_bill_total]
--      ,[portal_bill_total_excl_vat]
      ,[output_wip_balance]
--      ,[output_wip_contingent_wip]
--      ,[output_wip_current_value_of_fixed_fee_wip]
--      ,[output_wip_fixed_fee_value]
--      ,[output_wip_hourly_rate]
--      ,[output_wip_other_tbc_wip]
--      ,[output_wip_total_output_wip]
--      ,[output_wip_annual_retainer_wip]
--      ,[output_wip_secondment_wip]
--      ,[output_wip_percentage_complete]
--      ,[output_wip_fixed_fee_wip]
--      ,[chargeable_minutes_recorded]
--      ,[output_wip_internal_no_charge]
--      ,[client_account_last_posting_date]
--      ,[amount_paid_bill]
--      ,[output_wip_current_value_of_fixed_fee_wip_new]
--      ,[portal_status]
--      ,[total_amount_bill_non_comp]
  FROM [red_dw].[dbo].[fact_finance_summary] WITH (NOLOCK)



GO
