SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE VIEW [dbo].[vis_view_dim_detail_plot_details]
AS 

SELECT  [dim_detail_plot_detail_key]
--      ,[source_system_id]
--      ,[client_code]
--      ,[matter_number]
      ,[development]
--      ,[anticipated_date_confirmed]
--      ,[anticipated_date_of_mortgage_offer]
--      ,[anticipated_legal_completion_date]
--      ,[ate_received]
--      ,[atp_received]
--      ,[condition_date]
--      ,[confirmation_of_readiness_to_exchange]
--      ,[contractual_docs_sent_to_p_sols]
--      ,[date_info_received]
      ,[date_of_acknowledgement]
      ,[date_of_search_results]
      ,[deposit_money_received]
--      ,[documents_sent_to_p_sols]
--      ,[enquires_raised]
--      ,[enquires_satisfied]
--      ,[address_of_part_exchange]
--      ,[agency]
--      ,[all_info_received]
--      ,[atp_received_from_homebuy_agent]
--      ,[bardsley_development]
      ,[barratt_manchester_developments]
--      ,[barratt_mercia]
--      ,[car_parking_lease]
--      ,[contracts_exchanged]
--      ,[cumbria_lot]
      ,[david_wilson_homes_limited_developments]
      ,[greenfields_place_development_company_limited_developments]
--      ,[have_enquires_been_satisfied]
--      ,[have_p_sols_received_signed_docs_from_client]
--      ,[have_we_received_atp]
--      ,[leasehold_freehold]
      ,[lender]
      ,[manchester_ship_canal_developments_advent_limited]
--      ,[p_sols_ack_receipt_of_docs]
--      ,[p_sols_applied_for_searches]
--      ,[p_sols_confirmed_anticipated_date_of_mortgage_offer]
--      ,[p_sols_confirmed_ready_to_exchange]
--      ,[p_sols_prepared_and_submitted_htb_undertakings]
--      ,[p_sols_raised_enquires]
--      ,[p_sols_received_deposit_money]
--      ,[p_sols_received_formal_instruction]
--      ,[p_sols_received_mortgage_offer]
--      ,[p_sols_received_search_fees_money]
--      ,[p_sols_received_search_results]
--      ,[p_sols_received_signed_contract_from_client]
--      ,[p_sols_requested_formal_reservation_extension]
      ,[persimmon_homes_limited_development]
      ,[psplot_number]
--      ,[purchasers_2_full_address]
--      ,[purchasers_3_full_address]
--      ,[purchasers_4_full_address]
--      ,[purchasers_full_address]
      ,[purelake_new_homes_limited]
--      ,[reason_contract_not_received]
--      ,[reason_for_delay_in_exchange]
--      ,[reason_for_deposit_money_delay]
--      ,[reason_for_info_not_received]
--      ,[received_all_correct_and_relevent_htb_undertakings]
--      ,[received_ate_from_homebuy_agent]
      ,[thomas_jones_sons_limited_development]
      ,[type_of_lease]
      ,[type_of_scheme]
--      ,[type_of_transfer]
--      ,[formal_instruction_received]
--      ,[htb_undertakings_received]
      ,[mortgage_offer_received]
      ,[p_sols_anticipate_exchange_of_contracts]
      ,[p_sols_received_contract]
--      ,[pscompletion_date]
--      ,[psexpiry_of_reservation_period]
--      ,[reservation_extension_requested]
      ,[reservation_received]
--      ,[reservation_signed]
--      ,[search_fee_money_received]
--      ,[searches_applied]
--      ,[signed_docs_received]
--      ,[dss_create_time]
--      ,[dss_update_time]
      ,[exchange_date]
--      ,[exchange_date_combined]
--      ,[checklist]
--      ,[counterpart_lease_received]
--      ,[date_builder_plans]
--      ,[date_documents_sent]
--      ,[date_for_next_reminder]
      ,[date_of_exchange]
      ,[developer]
      ,[eccleston_homes_ltd]
--      ,[email_letter_reservation_extension]
--      ,[estimated_completion_date]
--      ,[exhange_letters_required]
--      ,[fifth_incentive_description]
--      ,[file_number_part_exchange]
--      ,[first_incentive_description]
--      ,[first_step_group_limited]
--      ,[fourth_incentive_description]
--      ,[heard_from_purchasers_solicitors]
--      ,[incentives]
--      ,[lender_present]
--      ,[lenders_details_present]
--      ,[outstanding_documentation]
--      ,[postal_address]
--      ,[pro_forma_required]
--      ,[ps_conditional]
--      ,[received_builder_plans]
--      ,[requesting_confirmation]
--      ,[second_incentive_description]
--      ,[sixth_incentive_description]
--      ,[third_incentive_description]
FROM [red_dw].[dbo].[dim_detail_plot_details] WITH (NOLOCK)


GO
