SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- ==============================================================================
-- DBMS Name       :     SQL Server
-- Script Name     :     get_bsc_client_score
-- Description     :     Generated
  -- Generated by   :    WhereScape RED Version 6.6.3.0 (build 121012)
-- Generated for   :     Weightmans
-- Author          :     Graeme Boag
-- ==============================================================================
-- Notes / History
-- 02/07/2015 Graeme Boag  Function to derive the BSC Rollup Score

-- DROP FUNCTION [dbo].[get_bsc_rollup_score] -- Will need to be manuallydropped before it will compile in RED


CREATE FUNCTION [dbo].[get_bsc_rollup_score]
(
 @p_score              decimal(18,6)
) RETURNS decimal(18,6)
AS
BEGIN


  --===============================================================
  -- Control variables used in most programs
  --===============================================================
  DECLARE
  @v_score    decimal(18,6) -- RETURN value

  SET @v_score= NULL

  SET @v_score =
    CASE
      WHEN @p_score > 2
	  THEN 3
      WHEN @p_score BETWEEN 1 AND 2
        THEN 1.5
      WHEN @p_score < 1
	  THEN 0
      ELSE 0
    END

   RETURN @v_score


END

GO
