SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- ==============================================================================
-- DBMS Name       :     SQL Server
-- Script Name     :     get_mfs_target_value
-- Description     :     Generated
  -- Generated by   :    WhereScape RED Version 6.8.6.0 (build 160602-123844)
-- Generated for   :     Weightmans
-- Author          :     Stephen Daffern
-- ==============================================================================
-- Notes / History
--

CREATE  FUNCTION [dbo].[get_mfs_scores]
(
 @p_pot         varchar(50),
 @p_metric      varchar(100),
 @p_snapshotdate datetime,
 @p_actual decimal(18,2),
 @p_aggregate varchar(1)
) RETURNS decimal(18,6)
AS
BEGIN


  --===============================================================
  -- Control variables used in most programs
  --===============================================================
  DECLARE
  @v_score     decimal(18,6) -- RETURN value

  SET @v_score = NULL

  BEGIN




  SELECT @v_score = isnull(score,-1)
    FROM [ds_sh_mfs_targets]
   WHERE pot =@p_pot and @p_actual between target_lower and target_upper and metric = @p_metric and @p_snapshotdate between dss_start_date and dss_end_date
   END

RETURN  CASE WHEN @p_actual IS NULL

AND @p_aggregate = 'N'

THEN -1

WHEN @p_actual IS NULL
AND @p_aggregate = 'Y'
THEN 0

--WHEN @p_actual IS NOT NULL
--AND @p_aggregate = 'Y'

--THEN 0
ELSE isnull(@v_score,0) END

END








GO
GRANT EXECUTE ON  [dbo].[get_mfs_scores] TO [SBC\SQL - LIVE DWH Developers Limited]
GO
