SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- ==============================================================================
-- DBMS Name       :     SQL Server
-- Script Name     :     get_mfs_target_value
-- Description     :     Generated
  -- Generated by   :    WhereScape RED Version 6.8.6.0 (build 160602-123844)
-- Generated for   :     Weightmans
-- Author          :     Stephen Daffern
-- ==============================================================================
-- Notes / History
--

CREATE  FUNCTION [dbo].[get_mfs_target_value]
(
 @p_pot         varchar(50),
 @p_metric      varchar(100),
 @p_snapshotdate datetime
) RETURNS decimal(18,6)
AS
BEGIN


  --===============================================================
  -- Control variables used in most programs
  --===============================================================
  DECLARE
  @v_target     decimal(18,6) -- RETURN value

  SET @v_target = NULL

  BEGIN


  SELECT @v_target = target
    FROM [ds_sh_mfs_targets]
   WHERE pot =@p_pot and [tier] = 'green' and metric = @p_metric and @p_snapshotdate between dss_start_date and dss_end_date
   END

RETURN @v_target

END



GO
