SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[datetimelocal] (@UTCDATE DATETIME)
RETURNS DATETIME
AS

BEGIN
	          
     DECLARE @LOCALDATETIME DATETIME

     SELECT @LOCALDATETIME = 
	 CASE WHEN CAST(@UTCDATE AS TIME) = '00:00:00.0000000' THEN @UTCDATE
	 ELSE
	 CONVERT(datetime, SWITCHOFFSET(@UTCDATE, DATEPART(TZOFFSET, 
     @UTCDATE AT TIME ZONE 'GMT Standard Time')))
     END   
     RETURN @LOCALDATETIME
END
GO
GRANT EXECUTE ON  [dbo].[datetimelocal] TO [db_ssrs_dynamicsecurity]
GO
