CREATE TABLE [CIS].[MIULeadLinkedSnapshot]
(
[case_id] [int] NOT NULL,
[Client] [char] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[Matter] [char] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[CIS Reference] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Date Closed in FED] [datetime] NULL,
[Date Opened in FED] [datetime] NULL,
[Insured Name] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[FeeEarner] [varchar] (88) COLLATE Latin1_General_CI_AS NULL,
[ID] [varchar] (8000) COLLATE Latin1_General_CI_AS NULL,
[No. of Claimants] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[RTA Date] [datetime] NULL,
[Date Received] [datetime] NULL,
[Month Instructions Received] [char] (3) COLLATE Latin1_General_CI_AS NULL,
[Last 12 Months] [datetime] NULL,
[Elapsed Days] [int] NULL,
[Fixed Fee] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[GuidNumber] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Date Closed/declared dormant] [datetime] NULL,
[BlankColumn] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[Date MI Updated] [datetime] NULL,
[Date re-opened] [datetime] NULL,
[Estimated Final Fee] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Status] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Outcome] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Policyholder Involvement] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Fraud Type] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[MI Reserve] [decimal] (19, 4) NULL,
[BlankColumn2] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[Date Pleadings Issued] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Paid prior to instruction] [decimal] (38, 2) NULL,
[Settlement Value] [decimal] (38, 2) NULL,
[Fees] [numeric] (38, 2) NULL,
[Net Savings] [numeric] (38, 2) NULL,
[Potential Recovery] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Audit] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Narrative] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Gunum] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[date_closed] [datetime] NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Weightmans Fee Earner] [varchar] (81) COLLATE Latin1_General_CI_AS NULL,
[FedStatus] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
[Master date closed/ dormant] [datetime] NULL,
[Master date MI updated] [datetime] NULL,
[Master Status] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Master Outcome] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Master settlement value] [decimal] (13, 2) NULL,
[Master fees] [decimal] (13, 2) NULL,
[Master net savings] [decimal] (13, 2) NULL,
[ReportingTab] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[FeeEarnerCode] [char] (4) COLLATE Latin1_General_CI_AS NOT NULL,
[SAP_Open] [varchar] (9) COLLATE Latin1_General_CI_AS NOT NULL,
[WIPBal] [decimal] (13, 2) NOT NULL,
[TotalProfitCostsBilled] [money] NULL,
[ProfitCostsVAT] [money] NULL,
[SAPClosedDate] [smalldatetime] NULL,
[Date Claim Concluded] [datetime] NULL,
[Month Claim Concluded] [char] (3) COLLATE Latin1_General_CI_AS NULL,
[Year Claim Concluded] [int] NULL,
[Incident Location] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Claimant Postcode] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[Present Position] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Date of repudiation] [datetime] NULL,
[Date Proceedings Issued] [datetime] NULL,
[Reporting Level] [int] NOT NULL,
[GuidTab] [int] NOT NULL,
[Is this the lead file?] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Linked File] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Lead File Matter Reference] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Work Type] [char] (40) COLLATE Latin1_General_CI_AS NULL,
[Referral Reason] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Claimant Solicitor] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Reason For Litigation] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Delegated] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Fixed Fee Linked] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Suspicion Of Fraud] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Does Claimant Have A PI Claim] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Credit Hire] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Has The Claimant Got A CFA] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Present Position Linked] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Damages Reserve Held (before payment)] [decimal] (19, 4) NULL,
[Damages Payments To Date] [decimal] (38, 2) NULL,
[Personal Injury Paid] [decimal] (38, 2) NULL,
[Special Damages (miscellaneous) Paid] [decimal] (38, 2) NULL,
[Credit Hire Paid] [decimal] (38, 2) NULL,
[Damages Reserve Outstanding] [decimal] (38, 2) NULL,
[Opponents Costs Reserve Held (before payments)] [decimal] (19, 4) NULL,
[Opponents Costs Paid To Date (Profit costs,Disbursements and VAT)] [decimal] (38, 2) NULL,
[Opponents Cost Reserve Outstanding] [decimal] (38, 2) NULL,
[Defence Costs Reserve Held (before payments)] [decimal] (19, 4) NULL,
[Defence Costs Billed To Date] [numeric] (38, 2) NULL,
[Defence Costs Reserve Outstanding] [numeric] (38, 2) NULL,
[ Total Reserve (before payments)] [decimal] (21, 4) NULL,
[Total Paid To Date] [numeric] (38, 2) NULL,
[Total Outstanding Reserve] [decimal] (21, 4) NULL,
[Outcome Linked] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Date Damages Concluded] [datetime] NULL,
[Date Costs Settled] [datetime] NULL,
[Opponent Total Costs Claimed] [decimal] (38, 2) NULL,
[Opponents Total Costs Paid] [decimal] (38, 2) NULL,
[Opponents Disbursements Paid] [decimal] (38, 2) NULL,
[Are we Pursuing a Recovery?] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Total Recovered] [decimal] (15, 2) NULL,
[Profit Costs Billed To Date (net of VAT)] [numeric] (38, 2) NULL,
[Disbursement Costs Billed To Date] [numeric] (38, 2) NULL,
[Total Billed To Date] [numeric] (38, 2) NULL,
[Date Of Last Bill] [datetime] NULL,
[Co-op Fraud type] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Co-op Fraud Master date closed/ dormant] [datetime] NULL,
[Co-op Fraud Master date MI updated] [datetime] NULL,
[Co-op Fraud Master Status] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Co-op Fraud) Master Outcome] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Co-op Fraud) Master settlement value] [decimal] (13, 2) NULL,
[Co-op Fraud) Master fees] [decimal] (13, 2) NULL,
[Co-op Fraud) Master net savings] [decimal] (13, 2) NULL,
[Court Name] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Damages Reserve Held LeadLinked] [decimal] (19, 4) NULL,
[Opponents Costs Reserve Held LeadLinked] [decimal] (19, 4) NULL,
[Defence Costs Reserve Held LeadLinked] [decimal] (19, 4) NULL,
[Proceedings Issued Y/N] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[File Level WIP] [decimal] (13, 2) NULL,
[File Level O/S Disbursements] [decimal] (13, 2) NULL,
[File Level Client Balance] [decimal] (13, 2) NULL,
[File Level Office Balance] [decimal] (13, 2) NULL,
[File Level Unpaid Bills] [decimal] (13, 2) NULL,
[Co-op Fraud) Reason for re-open] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Co-op Fraud) Reason for Litigation] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Trial date] [datetime] NULL,
[Date Of last Activity] [datetime] NULL,
[Underwriting Referral Made?] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[ABI Fraud Proven] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Is this a fraud ring] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Year Period] [int] NULL,
[Period] [varchar] (11) COLLATE Latin1_General_CI_AS NULL,
[InsertedDate] [datetime] NULL
) ON [PRIMARY]
GO
