CREATE TABLE [dbo].[FSPRevenueTargets2223_V2]
(
[Division] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Department] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Team] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Office Location] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Cascade No] [float] NULL,
[Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Surname] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Full Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Job Code ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Casehandler] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Contract Weekly Hours] [float] NULL,
[Date From] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date To] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[May] [float] NULL,
[June] [float] NULL,
[July] [float] NULL,
[Aug] [float] NULL,
[Sept] [float] NULL,
[Oct] [float] NULL,
[Nov] [float] NULL,
[Dec] [float] NULL,
[Jan] [float] NULL,
[Feb] [float] NULL,
[Mar] [float] NULL,
[Apr] [float] NULL,
[F26] [float] NULL,
[Total] [float] NULL,
[Check] [float] NULL
) ON [PRIMARY]
GO
