CREATE TABLE [dbo].[KHudmiparisk]
(
[fileid] [bigint] NULL,
[rowguid] [char] (36) COLLATE Latin1_General_BIN NULL,
[cbobusinessline] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbocomplaintcat] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbodiscipaction] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cboformalfind] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbohandlinglit] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cboleofeeimpose] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cboleoinvolved] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cboliable] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbonaturematter] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbooffclaimle] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbopaclaimaros] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbopracticearea] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cboricause] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbostatusclosur] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbostatuscompla] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cbotopupnotif] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[cboweighteam] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[curcompenpaid] [money] NULL,
[curcompenreser] [money] NULL,
[curcostspaid] [money] NULL,
[curcostswritoff] [money] NULL,
[curdamspaidrisk] [money] NULL,
[curricostsres] [money] NULL,
[curridamagesres] [money] NULL,
[dteclosed] [datetime] NULL,
[dtecomplrecris] [datetime] NULL,
[dtedamagespaid] [datetime] NULL,
[dtediscovery] [datetime] NULL,
[dteinsnotified] [datetime] NULL,
[dteinternalnoti] [datetime] NULL,
[txtbcmname] [nvarchar] (60) COLLATE Latin1_General_BIN NULL,
[txtcasemanname] [nvarchar] (60) COLLATE Latin1_General_BIN NULL,
[txtcourtofissue] [nvarchar] (60) COLLATE Latin1_General_BIN NULL,
[txtorigcliname] [nvarchar] (60) COLLATE Latin1_General_BIN NULL,
[txtorigclmatno] [nvarchar] (60) COLLATE Latin1_General_BIN NULL,
[txtothercause] [nvarchar] (60) COLLATE Latin1_General_BIN NULL,
[dss_create_time] [datetime] NULL,
[dss_update_time] [datetime] NULL,
[cbomattyperis] [nvarchar] (15) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
