CREATE TABLE [dbo].[RMLease100kAllRecords]
(
[client] [char] (8) COLLATE Latin1_General_CI_AS NULL,
[matter] [char] (8) COLLATE Latin1_General_CI_AS NULL,
[case_id] [int] NOT NULL,
[TitleNumber] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Demisedpremises] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Date] [date] NULL,
[Originallandlord] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Originaltenant] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[OriginalGuarantor] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Term] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Originalrent] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[VATexclusive] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Nextreviewdate] [date] NULL,
[Upwardsonly] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Basisofreview] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Repairobligation] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Partstoberepaired] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Decoration] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Assignwhole] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Assignpart] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Underletwhole] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Underletpart] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Groupsharing1] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Groupsharing2] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Usepermitted] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Otherusespermitted] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Specificprohibiteduse] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Structuralandexternal1] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Structuralandexternal2] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Internal1] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Internal2] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Payablebytenant] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Landlordsservices] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Insuranceeffectedby] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Premiumpayablebytenant] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Policyrisks] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Breakoptionifdamagenotremedied] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Rentsuspension] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Landlordsbreakoption] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[ConditionsA] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Tenantsbreakoption] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[ConditionsB] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Landlordsrights] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Tenantsrights] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[LTA1954] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Typeoflease] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Landlordsconsent] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Licenceforalterations] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Worksdisregardedonrentreview] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Reinstatementrequired] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Otherrelevantleaseterms] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[PRO997] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO956] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO957] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO958] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO960] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO998] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO963] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO964] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO965] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO959] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO961] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO962] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO772Text] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[NewRentalValue] [decimal] (18, 2) NULL,
[Term Start Date] [date] NULL,
[Term End Date] [date] NULL
) ON [PRIMARY]
GO
