CREATE TABLE [dbo].[FixedFee_JL]
(
[Client Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter Number] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter Description] [varchar] (200) COLLATE Latin1_General_BIN NULL,
[client_name] [char] (80) COLLATE Latin1_General_BIN NULL,
[Fed Code] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Handler] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Department] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Division] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Original Handler] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[Original Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Original Department] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[work_type_name] [char] (40) COLLATE Latin1_General_BIN NULL,
[output_wip_fee_arrangement] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[fixed_fee_amount] [numeric] (13, 2) NULL,
[present_position] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[outcome_of_case] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[date_claim_concluded] [datetime] NULL,
[defence_costs_billed] [numeric] (13, 2) NULL,
[output_wip_fixed_fee_value] [numeric] (13, 2) NULL,
[wip] [numeric] (13, 2) NULL,
[total_amount_bill_non_comp] [numeric] (13, 2) NULL,
[final_bill_date] [datetime] NULL,
[Billed Amount Write Off] [numeric] (38, 2) NULL,
[Billed Hours Write Off] [numeric] (38, 5) NULL,
[WIP Amount Hours Write Off] [numeric] (38, 2) NULL,
[WIP Hours Write Off] [numeric] (38, 5) NULL,
[WIP Over 90 days] [numeric] (38, 2) NULL,
[Chargeable Hours Recorded] [numeric] (17, 6) NULL,
[date_opened_case_management] [datetime] NULL,
[date_closed_case_management] [datetime] NULL
) ON [PRIMARY]
GO
