CREATE TABLE [dbo].[RMLetPortfolioAllRecords]
(
[client] [char] (8) COLLATE Latin1_General_CI_AS NULL,
[matter] [char] (8) COLLATE Latin1_General_CI_AS NULL,
[case_id] [int] NOT NULL,
[TitleNumber] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Demisedpremises] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Date] [date] NULL,
[Originallandlord] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Originaltenant] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[OriginalGuarantor] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Term] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Originalrent] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Nextreviewdate] [date] NULL,
[Upwardsonly] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Basisofreview] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Repairobligation] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Assignment] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Underletting] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Usepermitted] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Otherusespermitted] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Servicechargepayable] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Insuranceeffectedby] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Landlordsbreakoption] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[ConditionA] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Tenantsbreakoption] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[ConditionB] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[LTA1954] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Otherrelevantleaseterms] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[PRO990] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO991] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO992] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO993] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO994] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO995] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO996] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Term Start Date] [date] NULL,
[Term End Date] [date] NULL
) ON [PRIMARY]
GO
