CREATE TABLE [dbo].[demo_20180420]
(
[Client Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter Number] [char] (8) COLLATE Latin1_General_BIN NULL,
[MS Client Code] [nvarchar] (12) COLLATE Latin1_General_BIN NULL,
[MS Matter Number] [nvarchar] (20) COLLATE Latin1_General_BIN NULL,
[Matter Description] [varchar] (200) COLLATE Latin1_General_BIN NULL,
[Date Case Opened] [datetime] NULL,
[Date Case Closed] [datetime] NULL,
[Date Instructions Received] [datetime] NULL,
[Date Claim Concluded] [datetime] NULL,
[Claim Concluded Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Outcome of Case] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Case Manager Name] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[Case Manager] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[FTE] [numeric] (18, 16) NULL,
[Team Manager] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[TM Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[TM] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[Division] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Department] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Branch Name] [char] (40) COLLATE Latin1_General_BIN NULL,
[File Department Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[File Department] [char] (40) COLLATE Latin1_General_BIN NULL,
[Work Type Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[Work Type] [char] (40) COLLATE Latin1_General_BIN NULL,
[Client Group Name] [varchar] (40) COLLATE Latin1_General_BIN NULL,
[Client Name] [char] (80) COLLATE Latin1_General_BIN NULL,
[Client Sector] [char] (40) COLLATE Latin1_General_BIN NULL,
[Segment] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Client Sub-sector] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[claimantsols_name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Claimant's Solicitors Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Name of Claimant's Firm] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[Claimant Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Claimant's DOB] [datetime] NULL,
[Number of Claimants] [numeric] (13, 2) NULL,
[Policy Holder Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insurer Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Insurer Client Reference] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Insured Department] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insured Department Depot Postcode] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insured Client Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Insured Client Reference] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Court Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Court Reference] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Present Position] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Track] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Suspicion of Fraud?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Referral Reason] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Fixed Fee] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Proceedings Issued] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Proceedings Issued] [datetime] NULL,
[Accident Location] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Incident Date] [datetime] NULL,
[Incident Location] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Type of Injury] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Injury Type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Description of Injury] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Engineer Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Credit Hire] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Lead Follow] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Linked File?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Lead File?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Lead File Matter Number] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Associated Matter Numbers] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Work Referral?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Fraud Status] [datetime] NULL,
[Weightmans Comments] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date of Current Estimate to Complete Retainer] [datetime] NULL,
[Date Letter of Claim] [datetime] NULL,
[Date Initial Report Sent] [datetime] NULL,
[Date of Pre-Trial Report] [datetime] NULL,
[Date of Trial] [datetime] NULL,
[Trial Window] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Start of Trial Window] [datetime] NULL,
[Date End Of Trial Window] [datetime] NULL,
[Infant Approval] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[MoJ stage] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Reason for Instruction] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Sub Report] [datetime] NULL,
[Closure Report] [datetime] NULL,
[Liability Issue] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Delegated] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Litigated] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Claimants Costs Received] [datetime] NULL,
[Date Costs Settled] [datetime] NULL,
[Interim Costs Payments] [numeric] (13, 2) NULL,
[Fraud Savings] [numeric] (13, 2) NULL,
[Case Classification] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[status_on_instruction] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[reason_for_litigation] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Total MI Exceptions] [int] NULL,
[Total Critical MI Exceptions] [bit] NULL,
[final_bill_date_grp] [datetime] NULL,
[Last Bill Date] [datetime] NULL,
[Date of Final Bill] [datetime] NULL,
[Leaver?] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Date of Last Time Posting] [datetime] NULL,
[Client Account Balance of Matter] [numeric] (13, 2) NULL,
[work_type_group] [char] (40) COLLATE Latin1_General_BIN NULL,
[Instruction Type] [char] (60) COLLATE Latin1_General_BIN NULL,
[Repudiation - outcome] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[elapsed_days_closed] [int] NULL,
[elapsed_days_conclusion] [int] NULL,
[elapsed_days_damages] [int] NULL,
[elapsed_days_costs] [int] NULL,
[elapsed_days_costs_received_to_settle] [int] NULL,
[elapsed_days_costs_to_settle] [int] NULL,
[elapsed_days_live_files] [int] NULL,
[elapsed_days] [int] NULL,
[damages_interims] [numeric] (13, 2) NULL,
[damages_paid] [numeric] (13, 2) NULL,
[damages_paid_to_date] [numeric] (13, 2) NULL,
[damages_reserve] [numeric] (13, 2) NULL,
[damages_reserve_initial] [numeric] (13, 2) NULL,
[damages_reserve_net] [numeric] (13, 2) NULL,
[defence_costs_billed] [numeric] (13, 2) NULL,
[defence_costs_reserve] [numeric] (13, 2) NULL,
[defence_costs_reserve_initial] [numeric] (13, 2) NULL,
[defence_costs_reserve_net] [numeric] (13, 2) NULL,
[detailed_assessment_costs_claimed_by_claimant] [numeric] (13, 2) NULL,
[detailed_assessment_costs_paid] [numeric] (13, 2) NULL,
[disbursements_billed] [numeric] (13, 2) NULL,
[fixed_fee_amount] [numeric] (13, 2) NULL,
[indemnity_spend] [numeric] (13, 2) NULL,
[indemnity_spend_net_recoveries] [numeric] (13, 2) NULL,
[interlocutory_costs_paid_to_claimant] [numeric] (13, 2) NULL,
[opponents_disbursements_paid] [numeric] (13, 2) NULL,
[other_defendants_costs_paid] [numeric] (13, 2) NULL,
[other_defendants_costs_reserve] [numeric] (13, 2) NULL,
[other_defendants_costs_reserve_initial] [numeric] (13, 2) NULL,
[recovery_claimants_damages_via_third_party_contribution] [numeric] (13, 2) NULL,
[recovery_defence_costs_via_third_party_contribution] [numeric] (13, 2) NULL,
[recovery_defence_costs_from_claimant] [numeric] (13, 2) NULL,
[percentage_total_savings_damages_and_costs] [numeric] (13, 2) NULL,
[personal_injury_paid] [numeric] (13, 2) NULL,
[special_damages_miscellaneous_paid] [numeric] (13, 2) NULL,
[special_damages_miscellaneous_reserve] [numeric] (13, 2) NULL,
[total_amount_billed] [numeric] (13, 2) NULL,
[total_costs_recovery] [numeric] (13, 2) NULL,
[total_damages_and_tp_costs_reserve] [numeric] (13, 2) NULL,
[total_paid] [numeric] (13, 2) NULL,
[total_paid_net_recoveries] [numeric] (13, 2) NULL,
[total_recovery] [numeric] (13, 2) NULL,
[total_reserve] [numeric] (13, 2) NULL,
[total_reserve_initial] [numeric] (13, 2) NULL,
[total_reserve_net] [numeric] (13, 2) NULL,
[total_savings] [numeric] (13, 2) NULL,
[total_savings_damages] [numeric] (13, 2) NULL,
[total_savings_damages_and_costs] [numeric] (13, 2) NULL,
[total_savings_net_recoveries] [numeric] (13, 2) NULL,
[total_settlement_value_of_the_claim_paid_by_all_the_parties] [numeric] (13, 2) NULL,
[total_tp_costs_paid] [numeric] (13, 2) NULL,
[total_tp_costs_paid_to_date] [numeric] (13, 2) NULL,
[tp_costs_reserve] [numeric] (13, 2) NULL,
[tp_costs_reserve_initial] [numeric] (13, 2) NULL,
[tp_costs_reserve_net] [numeric] (13, 2) NULL,
[tp_total_costs_claimed] [numeric] (13, 2) NULL,
[total_costs_claimed] [numeric] (13, 2) NULL,
[total_costs_paid] [numeric] (13, 2) NULL,
[unpaid_disbursements] [numeric] (13, 2) NULL,
[vat_billed] [numeric] (13, 2) NULL,
[wip] [numeric] (13, 2) NULL,
[disbursement_balance] [numeric] (13, 2) NULL,
[client_account_balance_of_matter] [numeric] (13, 2) NULL,
[unpaid_bill_balance] [numeric] (13, 2) NULL,
[deposit_account_balance] [numeric] (13, 2) NULL,
[costs_to_date] [numeric] (13, 2) NULL,
[unbilled_time] [int] NULL,
[time_billed] [numeric] (13, 2) NULL,
[time_charge_value] [numeric] (13, 2) NULL,
[paid_disbursements] [numeric] (13, 2) NULL,
[defence_costs_billed_composite] [numeric] (16, 5) NULL,
[total_billed_disbursements_vat] [numeric] (16, 5) NULL,
[total_unbilled_disbursements_vat] [numeric] (16, 5) NULL,
[defence_costs_vat] [numeric] (16, 5) NULL,
[other_defendants_costs_reserve_net] [numeric] (13, 2) NULL,
[chargeable_minutes_recorded] [numeric] (13, 2) NULL
) ON [PRIMARY]
GO
