CREATE TABLE [dbo].[RoyalMailOneView_JL]
(
[Weightmans Reference] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Client Code] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Matter Number] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Matter Description] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Work Type Code] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Work Type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Property Contact] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Tenant Break Option] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[lease_report_leasehold_25k_100k] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[rolling_fixed_date] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[date_fixed_1] [datetime] NULL,
[date_fixed_2] [datetime] NULL,
[date_fixed_3] [datetime] NULL,
[date_fixed_4] [datetime] NULL,
[BE Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[BE Number] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date of Lease] [datetime] NULL,
[Demised Premises] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Property Team] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[countofdays] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[next_review_date] [datetime] NULL,
[Term End Date] [datetime] NULL,
[case_type_rmg] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[instruction_type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[postcode] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FixedDate] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[RentReviewDate] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[completion_date] [datetime] NULL,
[case_classification] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[present_position] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Open/Closed Case Status] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[date_opened_case_management] [datetime] NULL,
[No# Days Opened] [float] NULL
) ON [PRIMARY]
GO
