CREATE TABLE [ss].[InsuranceDataFile]
(
[Weightmans Reference] [varchar] (17) COLLATE Latin1_General_BIN NULL,
[Client Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter Number] [char] (8) COLLATE Latin1_General_BIN NULL,
[Nature of Claim] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Claim Category] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Type of Injury] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Does Claimant Have Personal Injury Claim?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Litigation Avoidable] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Clients Claim Handler] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Incident Location Postcode] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Has Claimant got a CFA?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Co-op Guid Ref Number] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[MOJ Apply] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Claimant in Person] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Delegated] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insured Sector] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Gender] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Legal Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Initial Glasgow Coma Scale] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Frontal Lobe Damage] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Level of Spinal Cord Injury] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Marital Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Motor Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Total Gross Reserve on Claim > £500,000?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Zurich Branch] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Zurich Line of Business] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insurer Client Ref] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Current Fraud Type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Initial Fraud Type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Potential Recovery] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[In Reciept of Payment Pack] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Engineer Instructed] [datetime] NULL,
[Date Vehicle Inspected] [datetime] NULL,
[Date of Engineers Report] [datetime] NULL,
[Date Repairs Commenced] [datetime] NULL,
[Date Satisfaction Note Signed] [datetime] NULL,
[Vehicle a Total loss] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Payment Pack Received] [datetime] NULL,
[CHO Vehicle Registration] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[CHO Postcode] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Hire Group Billed] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Hire Invoice Date] [datetime] NULL,
[Claimant Impecunious?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Are we Dealing with the Credit Hire?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Claim for Hire] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Penalties Paid] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Claim Type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[GTA] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Protocol] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Savings Area] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Spot Enquiry Made] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Vehicle Written Off] [datetime] NULL,
[CHV Date Hire Paid] [datetime] NULL,
[Costs Negotiators Used] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Are we Pursuing a Recovery?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Recovery Concluded] [datetime] NULL,
[Date Referral to Costs Unit] [datetime] NULL,
[Recovery Claimants Our Client Damages] [numeric] (13, 2) NULL,
[Sabre Closure Date] [datetime] NULL,
[Value of PAV/Repairs] [numeric] (13, 2) NULL,
[Interim Payments?] [numeric] (13, 2) NULL,
[Commercial Rate] [numeric] (13, 2) NULL,
[Current Estimate] [numeric] (13, 2) NULL,
[30-day sum] [numeric] (13, 2) NULL,
[60-day sum] [numeric] (13, 2) NULL,
[90-day sum] [numeric] (13, 2) NULL,
[General Damages Paid] [numeric] (13, 2) NULL,
[Special Damages Paid] [numeric] (13, 2) NULL,
[Claimants Solicitors Hours Claimed] [numeric] (13, 2) NULL,
[Number of Claimants] [numeric] (13, 2) NULL,
[Number of Defendants] [numeric] (13, 2) NULL,
[% of Client's Liability Agreed Prior to Instruction] [numeric] (13, 2) NULL,
[% of Client's Liability Awarded/Agreed Post insts/applied] [numeric] (13, 2) NULL,
[% of Contributory Negligence Agreed] [numeric] (13, 2) NULL,
[Annual Periodic - 100%] [numeric] (13, 2) NULL,
[Annual Periodic Net] [numeric] (13, 2) NULL,
[Final Total Costs] [numeric] (13, 2) NULL,
[Global Settlement] [numeric] (13, 2) NULL,
[Liability Initial Advice] [numeric] (13, 2) NULL,
[Liability Updated Advice] [numeric] (13, 2) NULL,
[PCT annual contribution (period 1)] [numeric] (13, 2) NULL,
[PCT annual contribution (period 2)] [numeric] (13, 2) NULL,
[PCT annual contribution (period 3)] [numeric] (13, 2) NULL,
[PCT annual contribution (period 4)] [numeric] (13, 2) NULL,
[Amount of Debt] [numeric] (13, 2) NULL,
[Hire Reserve] [numeric] (13, 2) NULL,
[General Damages Reserve Current] [numeric] (13, 2) NULL,
[General Damages Reserve Initial] [numeric] (13, 2) NULL,
[Special Damages Reserve Current] [numeric] (13, 2) NULL,
[Special Damages Reserve Initial] [numeric] (13, 2) NULL,
[Converge Disease Reserve] [numeric] (13, 2) NULL,
[Claimant Medical Expert] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Division Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Ageas Case Handler] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Ageas Instruction Type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Zurich Claimant's Solicitors] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Zurich Claimant] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Zurich Claim Number] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Zurich Policy Holder Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Location of Claimant's Workplace] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Location of Claimant's Solicitors] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Supervisor Review Date] [datetime] NULL,
[Supervisor Comment] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Case Manager Review Comment] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Settlement Form sent to Zurich] [datetime] NULL,
[Reason for Litigation] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Sub Reason Litigation] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[LIT0601 Planned Date] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[Repudiated - Insurance] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Historic Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Hire Paid] [numeric] (13, 2) NULL,
[Hire Claimed] [numeric] (13, 2) NULL,
[Hire Paid Rolling] [int] NULL,
[tier_1_3_case] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Reason for Instruction] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Reason Litigation not Avoided] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Reason for Re-opening Request] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[AIG Department] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[AIG Instructing Office] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[AIG Current Fee Scale] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[AIG Hide Flag] [varchar] (1) COLLATE Latin1_General_BIN NULL,
[AIG Litigation Number] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[AIG Line of Business] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[CFA entered into before 1 April 2013] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date CNF sent] [datetime] NULL,
[Who Dropped the Claim out of Portal?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Initial Acknowledgement sent to Claims Handler] [datetime] NULL,
[Date Indemnity Settled] [datetime] NULL,
[Name of Costs Negotiators] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Capita Stage of Settlement] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Joint Settlement Meeting] [datetime] NULL,
[Date Re-opened] [datetime] NULL,
[Ageas/Tesco Office] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Name of Instructing Insurer] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[ReportTab] [varchar] (4) COLLATE Latin1_General_CI_AS NOT NULL,
[YearFinalBill_Zurich] [int] NULL,
[Ageas Track] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Client Name - Quinn Direct] [varchar] (80) COLLATE Latin1_General_BIN NULL,
[GroupamaOutcome] [varchar] (21) COLLATE Latin1_General_CI_AS NOT NULL,
[Live Claim Ageas] [int] NOT NULL,
[Live Claim - Other Clients] [int] NOT NULL,
[Claim Type - Insurance] [varchar] (11) COLLATE Latin1_General_CI_AS NOT NULL,
[Credit Hire Organisation] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Repudiated/Settled] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Injury Type Group] [varchar] (21) COLLATE Latin1_General_CI_AS NULL,
[Settlement Basis] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Team Location] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Elapsed Days Live] [int] NULL,
[Outcome of Instruction] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Elapsed Days to Conclusion] [int] NULL,
[Elapsed Days to Costs Conclusion] [int] NULL,
[AIG Weightmans Department] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Days from Instructed to Opened] [decimal] (20, 2) NULL,
[Days from Instructed to Acknowledgement] [decimal] (20, 2) NULL,
[Days from Instructed to Intial Report Sent] [decimal] (20, 2) NULL,
[Elapsed Days from Instructed to Indemnity Settled] [decimal] (20, 2) NULL,
[Elapsed Days from Instructed to Costs Settled] [decimal] (20, 2) NULL,
[Elapsed Days from Instructed to Closed] [decimal] (20, 2) NULL,
[Live Elapsed Days from Date Instructed] [decimal] (20, 2) NULL,
[File Opened] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[Acknowledgement] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[Initial Report Sent] [varchar] (17) COLLATE Latin1_General_CI_AS NULL,
[AIG Filestatus] [varchar] (6) COLLATE Latin1_General_CI_AS NULL,
[Ageas Claim Status] [varchar] (11) COLLATE Latin1_General_CI_AS NOT NULL,
[Days to Open File] [int] NULL
) ON [PRIMARY]
GO
