CREATE TABLE [dbo].[InsuredClientSummaryData]
(
[Weightmans Client/Matter No] [varchar] (17) COLLATE Latin1_General_BIN NULL,
[MatterSphere Client/Matter No] [nvarchar] (33) COLLATE Latin1_General_BIN NULL,
[Matter Description] [varchar] (200) COLLATE Latin1_General_BIN NULL,
[Work Type] [char] (40) COLLATE Latin1_General_BIN NULL,
[Date Opened] [datetime] NULL,
[Date Closed] [datetime] NULL,
[Case Manager] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Department] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Client Group] [varchar] (40) COLLATE Latin1_General_BIN NULL,
[Client Name] [char] (80) COLLATE Latin1_General_BIN NULL,
[Client Sector] [char] (40) COLLATE Latin1_General_BIN NULL,
[Client Segment] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insured Client Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Insured Client Name (DS)] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[DST Insured Client Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insured Client Sector] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Client/Insured Client Sector] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Present Position] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Total Reserve (TRA076 + TRA080 + NMI519 + TRA078)] [numeric] (13, 2) NULL,
[Total Billed] [numeric] (13, 2) NULL,
[WIP] [numeric] (13, 2) NULL,
[Revenue 2015/2016] [numeric] (38, 5) NULL,
[Revenue 2016/2017] [numeric] (38, 5) NULL,
[Revenue 2017/2018] [numeric] (38, 5) NULL,
[Revenue 2018/2019] [numeric] (38, 5) NULL,
[Revenue 2019/2020] [numeric] (38, 5) NULL
) ON [PRIMARY]
GO
