CREATE TABLE [dbo].[NPG_Ongoing]
(
[Local authority] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Batch No] [float] NULL,
[Batch date] [datetime] NULL,
[Surveyor] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Substation Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Location] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Postcode] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Lease expiry date] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Term] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Premium] [money] NULL,
[Demise area] [float] NULL,
[Associated Rights] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Special conditions] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Plan No#] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F15] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Surrender required?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Landlord Title Number] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[LH title number] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Entity LH title vested in] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date of lease] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Landlord in original lease] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Tenant in original lease] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Title obtained] [datetime] NULL,
[Date Title checked] [datetime] NULL,
[Date documents produced] [datetime] NULL,
[Date documents approved] [datetime] NULL,
[Date engrossments issued] [datetime] NULL,
[Date Documents Completed] [datetime] NULL,
[Date sent for registration] [datetime] NULL,
[Date registration completed] [datetime] NULL,
[Date deeds sent to NPg] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
