CREATE TABLE [dbo].[post_matter_feedback_old]
(
[Quarter ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[client_organisation] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[client_name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[client_id] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[practice_area] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[lead_office] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[total_fees_billed] [float] NULL,
[client_sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[client_segment] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[matter_code] [float] NULL,
[lead_partner] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[matter_description] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[matter_owner] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[final_bill_date] [float] NULL,
[selection] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Speed of response] [float] NULL,
[Value] [float] NULL,
[Business understanding] [float] NULL,
[Sector knowledge] [float] NULL,
[Legal advice] [float] NULL,
[Commerciality] [float] NULL,
[Meet expectations] [float] NULL,
[Efficient] [float] NULL,
[Overall satisfaction] [float] NULL,
[Positives] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Improvements] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Recommendation] [float] NULL,
[9-10 reasons] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[7-8 reasons] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[1-6 reasons] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Priority ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Areas of interest] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
