CREATE TABLE [dbo].[CertasDetails240518]
(
[F1] [float] NULL,
[FileId] [float] NULL,
[FEDCaseID] [float] NULL,
[clNo] [float] NULL,
[MatterNumber] [float] NULL,
[fileDesc] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[fileResponsibleID] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[filePrincipleID] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[fileDept] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[fileType] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtPropertyName] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtaddress] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtTenure1] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtPropType] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtPetrolBrand] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtTitleNumber] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtTerm] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dteDOE] [datetime] NULL,
[dteDOR] [datetime] NULL,
[curOriginalRent] [float] NULL,
[curPurchPrice] [float] NULL,
[dteLeaseExpiry] [datetime] NULL,
[txtExtended] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtRentRevFreq] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dteRentRev1] [datetime] NULL,
[dteRentRev2] [datetime] NULL,
[dteRentRev3] [datetime] NULL,
[dteRentRev4] [datetime] NULL,
[dteRentRev5] [datetime] NULL,
[curPassingRent] [float] NULL,
[dteLandlordBrea] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dteTenantBreak] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dteSubLeaStart] [datetime] NULL,
[dteSubLeaEnd] [datetime] NULL,
[curSubLeaRent] [float] NULL,
[txtAssignation] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Documents Path] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
