CREATE TABLE [dbo].[STWImport260219]
(
[Client] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Matter] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[MSFileID] [float] NULL,
[cboPolicyType] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtYearOfAccoun] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dteIncidentDate] [datetime] NULL,
[cboPolSectGrp] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dteClosed] [datetime] NULL,
[cboClaimStat] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[cboSubsidiary] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[cboCauseDesc] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtCauseDescAdd] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[cboEffectDesc] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[txtSAPCode] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[cboWorkingDed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dteReopened] [datetime] NULL,
[dteCancelled] [datetime] NULL,
[curELDamRes] [float] NULL,
[curELRecRes] [float] NULL,
[curELInserDRes] [float] NULL,
[curELTPCostRes] [float] NULL,
[curELFeesRecRes] [float] NULL,
[curELInserTPRes] [float] NULL,
[curELOwnCostRes] [float] NULL,
[curELOwnCoReRes] [float] NULL,
[curELInrOwCoRes] [float] NULL,
[curMODamRes] [float] NULL,
[curMORecRes] [float] NULL,
[curMOInserDRes] [float] NULL,
[curMOPCostRes] [float] NULL,
[curMOFeesRecRes] [float] NULL,
[curMOInserTPRes] [float] NULL,
[curMOOwnCostRes] [float] NULL,
[curMOOwnCoReRes] [float] NULL,
[curMOInrOwCoRes] [float] NULL
) ON [PRIMARY]
GO
