CREATE TABLE [dbo].[ImportFailure]
(
[ID] [int] NOT NULL,
[clNo] [nvarchar] (12) COLLATE Latin1_General_CI_AS NOT NULL,
[fileNo] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[extFileID] [bigint] NULL,
[fileDesc] [nvarchar] (255) COLLATE Latin1_General_CI_AS NOT NULL,
[fileResponsibleID] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[filePrincipleID] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileDept] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileType] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileFundCode] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileCurISOCode] [nchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[fileStatus] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileCreated] [datetime] NULL,
[fileUpdated] [datetime] NULL,
[fileClosed] [datetime] NULL,
[fileSource] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[fileSection] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[fileSectionGroup] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[MattIndex] [int] NULL,
[Office] [int] NULL,
[brID] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[Partner] [bigint] NOT NULL,
[InsertDate] [datetime] NOT NULL,
[Imported] [datetime] NULL,
[StatusID] [tinyint] NOT NULL,
[error] [int] NULL,
[errormsg] [varchar] (2000) COLLATE Latin1_General_CI_AS NULL,
[NewMatterNumber] [int] NULL,
[BusinessLine] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[FEDCode] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
