CREATE TABLE [dbo].[ClientContactStage_GoLive]
(
[extContID] [int] NULL,
[clNo] [int] NULL,
[clName] [char] (60) COLLATE Latin1_General_CI_AS NOT NULL,
[clType] [int] NOT NULL,
[cbocligrp] [char] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[cboPartner] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[addid] [int] NULL,
[addLine1] [char] (40) COLLATE Latin1_General_CI_AS NULL,
[addLine2] [char] (40) COLLATE Latin1_General_CI_AS NULL,
[addLine3] [int] NULL,
[addLine4] [char] (40) COLLATE Latin1_General_CI_AS NULL,
[addLine5] [char] (40) COLLATE Latin1_General_CI_AS NULL,
[addPostCode] [char] (12) COLLATE Latin1_General_CI_AS NULL,
[addCountry] [int] NULL,
[addDXCode] [char] (20) COLLATE Latin1_General_CI_AS NULL,
[contType] [varchar] (12) COLLATE Latin1_General_CI_AS NOT NULL,
[contSalut] [char] (30) COLLATE Latin1_General_CI_AS NULL,
[contTitle] [char] (10) COLLATE Latin1_General_CI_AS NULL,
[contFirstNames] [char] (30) COLLATE Latin1_General_CI_AS NULL,
[contSurname] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[contSex] [int] NULL,
[contNotes] [int] NULL,
[contCreated] [datetime2] (3) NOT NULL,
[contEmail] [char] (40) COLLATE Latin1_General_CI_AS NULL,
[contTelHome] [char] (20) COLLATE Latin1_General_CI_AS NULL,
[contTelWork] [char] (20) COLLATE Latin1_General_CI_AS NULL,
[contTelMob] [char] (20) COLLATE Latin1_General_CI_AS NULL,
[contFAX] [char] (20) COLLATE Latin1_General_CI_AS NULL,
[OMSaddID] [int] NULL,
[DCFlag] [int] NULL,
[ClientIndex] [int] NULL,
[EntIndex] [int] NULL,
[feeUsrID] [int] NULL,
[brID] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[contSubType] [varchar] (12) COLLATE Latin1_General_CI_AS NOT NULL,
[InsertDate] [datetime2] (3) NOT NULL,
[Imported] [int] NULL,
[StatusID] [int] NOT NULL,
[error] [int] NOT NULL,
[errormsg] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[IsClient] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[NewClientID] [int] NULL
) ON [PRIMARY]
GO
