CREATE TABLE [dbo].[SegmentAPI300518]
(
[Client or Client Group] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Master client code ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[MSclID] [float] NULL,
[MSName] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Master Client Partner] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Segment] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[New sector - multiline or monoline] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[cboSubSegment] [float] NULL,
[Previous Yr Total PC FY] [money] NULL,
[Prev Period PC] [money] NULL,
[Selected Period PC] [money] NULL,
[% Difference] [money] NULL,
[F14] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F15] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F16] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F17] [money] NULL,
[F18] [money] NULL,
[F19] [money] NULL,
[F20] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F21] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F22] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F23] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F24] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F25] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F26] [money] NULL,
[F27] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F28] [money] NULL,
[F29] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F30] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F31] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F32] [money] NULL,
[F33] [money] NULL,
[F34] [money] NULL,
[F35] [money] NULL,
[F36] [money] NULL,
[F37] [money] NULL,
[F38] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F39] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F40] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F41] [money] NULL,
[F42] [money] NULL,
[F43] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F44] [money] NULL,
[F45] [money] NULL,
[F46] [money] NULL,
[F47] [money] NULL,
[F48] [money] NULL,
[F49] [money] NULL,
[F50] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F51] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F52] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F53] [money] NULL,
[F54] [money] NULL,
[F55] [money] NULL,
[F56] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F57] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F58] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F59] [money] NULL,
[F60] [money] NULL,
[F61] [money] NULL,
[F62] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F63] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F64] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
