CREATE TABLE [dbo].[FWMatterCreationStage]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[clNo] [nvarchar] (12) COLLATE Latin1_General_CI_AS NOT NULL,
[fileNo] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[extFileID] [bigint] NULL,
[fileDesc] [nvarchar] (255) COLLATE Latin1_General_CI_AS NOT NULL,
[fileResponsibleID] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[filePrincipleID] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileDept] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileType] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileFundCode] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF__FWMatterC__fileF__027D5126] DEFAULT ('NOCHG'),
[fileCurISOCode] [nchar] (3) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF__FWMatterC__fileC__0371755F] DEFAULT ('GBP'),
[fileStatus] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[fileCreated] [datetime] NULL CONSTRAINT [DF__FWMatterC__fileC__04659998] DEFAULT (getdate()),
[fileUpdated] [datetime] NULL,
[fileClosed] [datetime] NULL,
[fileSource] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF__FWMatterC__fileS__0559BDD1] DEFAULT ('IMPORT'),
[fileSection] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[fileSectionGroup] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[MattIndex] [int] NULL,
[Office] [int] NULL,
[brID] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[Partner] [bigint] NOT NULL,
[InsertDate] [datetime] NOT NULL CONSTRAINT [DF__FWMatterC__Inser__064DE20A] DEFAULT (getdate()),
[Imported] [datetime] NULL,
[StatusID] [tinyint] NOT NULL CONSTRAINT [DF__FWMatterC__Statu__07420643] DEFAULT ((0)),
[error] [int] NULL,
[errormsg] [varchar] (2000) COLLATE Latin1_General_CI_AS NULL,
[NewMatterNumber] [int] NULL,
[BusinessLine] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[FEDCode] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[SourceSystemID] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
