CREATE TABLE [dbo].[udDeedwill_20171025_DelRecs_BK]
(
[dwID] [bigint] NOT NULL,
[rowguid] [uniqueidentifier] NULL,
[clID] [bigint] NULL,
[fileID] [bigint] NULL,
[Created] [datetime] NULL,
[CreatedBy] [int] NULL,
[dwActionDate] [datetime] NULL,
[dwActive] [smallint] NULL,
[dwAddress] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[dwArchivedDate] [datetime] NULL,
[dwArcLLoc] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dwAuthBy] [int] NULL,
[dwBoxed] [bit] NULL,
[dwBoxTotal] [smallint] NULL,
[dwCheckedFiles] [bit] NULL,
[dwClientContact] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[dwDateOfDoc] [datetime] NULL,
[dwDeleted] [bit] NOT NULL,
[dwDeletedBy] [int] NULL,
[dwDeletedDate] [datetime] NULL,
[dwDesc] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dwDestroyDue] [datetime] NULL,
[dwDestroyDate] [datetime] NULL,
[dwFileNo] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[dwFullName] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dwHolder] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[dwInStorage] [bit] NULL,
[dwNote] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[dwOffLocation] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[dwOffsiteRef] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[dwRef] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[dwRemovedDate] [datetime] NULL,
[dwRetentionReas] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[dwRetentionType] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[dwRetrievalFor] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[dwRetrievalReas] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[dwRetrieveReq] [datetime] NULL,
[dwRetrieveReqBy] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[dwReturnDate] [datetime] NULL,
[dwStorageLoc] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[dwType] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[Status] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[dwOrigin] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
