CREATE TABLE [dbo].[SegmentAPI_20170621]
(
[ClientID] [float] NULL,
[historic_client_code] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[client_code] [float] NULL,
[client_name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[client_partner_name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[segment] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[cbosegment] [float] NULL,
[sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[cbosubsegment] [float] NULL,
[sub_sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[cbosector] [float] NULL,
[F12] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F13] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F14] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F15] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F16] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F17] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F18] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F19] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F20] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F21] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F22] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F23] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F24] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F25] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F26] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F27] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F28] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F29] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F30] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F31] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F32] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F33] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F34] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F35] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F36] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F37] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F38] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F39] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F40] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F41] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F42] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F43] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F44] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F45] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F46] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F47] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
