CREATE TABLE [dbo].[HealthcareSegmentAPI170522]
(
[client_name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[client_code] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[matter_client] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[MSCLiID] [float] NULL,
[MS Client Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[segment] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[sub_sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[New Segment] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[New Sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[New Subsector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[NewcboSegment] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[NewcboSector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[NewcboSubSegment] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F15] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F16] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F17] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F18] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F19] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F20] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F21] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F22] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F23] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F24] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F25] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F26] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F27] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F28] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F29] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F30] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F31] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F32] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
