CREATE SCHEMA [Omni]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [Omni] TO [SBC\SQL - DataReader on SVR-LIV-DWH-01]
GO
GRANT CONTROL ON SCHEMA:: [Omni] TO [SBC\SQL - DataReader on SVR-LIV-DWH-01]
GO
GRANT CREATE SEQUENCE ON SCHEMA:: [Omni] TO [SBC\SQL - DataReader on SVR-LIV-DWH-01]
GO
GRANT INSERT ON SCHEMA:: [Omni] TO [SBC\SQL - DataReader on SVR-LIV-DWH-01]
GO
GRANT SELECT ON SCHEMA:: [Omni] TO [SBC\SQL - DataReader on SVR-LIV-DWH-01]
GO
GRANT TAKE OWNERSHIP ON SCHEMA:: [Omni] TO [SBC\SQL - DataReader on SVR-LIV-DWH-01]
GO
GRANT UPDATE ON SCHEMA:: [Omni] TO [SBC\SQL - DataReader on SVR-LIV-DWH-01]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [Omni] TO [SBC\SQL - DataReader on SVR-LIV-DWH-01]
GO
