CREATE TABLE [dbo].[ds_sh_3e_user_sync_backup_20191113]
(
[timekeeperindex] [int] NULL,
[Entity] [int] NULL,
[TRE_user] [char] (36) COLLATE Latin1_General_BIN NULL,
[payrollid] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[firstname] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[surname] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[knownas] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[name] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[DOB] [datetime] NULL,
[prefix] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[gender] [varchar] (6) COLLATE Latin1_General_BIN NULL,
[email] [nvarchar] (320) COLLATE Latin1_General_BIN NULL,
[phonenumber] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[username] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[startdate] [datetime] NULL,
[office] [nvarchar] (16) COLLATE Latin1_General_BIN NULL,
[officename] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[address] [int] NULL,
[sitetype] [nvarchar] (16) COLLATE Latin1_General_BIN NULL,
[businessline] [nvarchar] (16) COLLATE Latin1_General_BIN NULL,
[team] [nvarchar] (16) COLLATE Latin1_General_BIN NULL,
[jobrole] [nvarchar] (16) COLLATE Latin1_General_BIN NULL,
[hrtitle] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[payrollid_BCM] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[ratetype] [varchar] (6) COLLATE Latin1_General_BIN NULL,
[defaultrate] [int] NULL,
[tkrtype] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[userstatusid] [int] NULL,
[userstatus] [varchar] (8) COLLATE Latin1_General_BIN NULL,
[leaverdate] [datetime] NULL,
[rate_class] [varchar] (16) COLLATE Latin1_General_BIN NULL,
[dss_create_time] [datetime] NULL,
[dss_update_time] [datetime] NULL,
[effstart] [datetime] NULL,
[employeeid] [char] (36) COLLATE Latin1_General_BIN NULL,
[ms_usrid] [int] NULL
) ON [WRK_TAB]
GO
