SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Emily Smith
-- Create date: 2020-09-23
-- Description:	#169090, new key date report
-- =============================================
CREATE PROCEDURE [dbo].[KeyDates]
(
	@DateFrom DATE,
	@DateTo DATE,
	@Department VARCHAR(MAX),
	@Team VARCHAR(MAX),
	@CaseManager VARCHAR(MAX),
	@ClientGroup VARCHAR(MAX),
	@ClientCode VARCHAR(MAX)
)
AS
BEGIN

	SET NOCOUNT ON;

	IF OBJECT_ID('tempdb..#Department') IS NOT NULL   DROP TABLE #Department
	IF OBJECT_ID('tempdb..#Team') IS NOT NULL   DROP TABLE #Team
	IF OBJECT_ID('tempdb..#CaseManager') IS NOT NULL   DROP TABLE #CaseManager
	IF OBJECT_ID('tempdb..#ClientGroup') IS NOT NULL   DROP TABLE #ClientGroup
	IF OBJECT_ID('tempdb..#ClientCode') IS NOT NULL   DROP TABLE #ClientCode

	SELECT ListValue  INTO #Department FROM Reporting.dbo.[udt_TallySplit](',', @Department)
	SELECT ListValue  INTO #Team FROM Reporting.dbo.[udt_TallySplit](',', @Team)
	SELECT ListValue  INTO #CaseManager FROM Reporting.dbo.[udt_TallySplit](',', @CaseManager)
	SELECT ListValue  INTO #ClientGroup FROM Reporting.dbo.[udt_TallySplit](',', @ClientGroup)
	SELECT ListValue  INTO #ClientCode FROM Reporting.dbo.[udt_TallySplit](',', @ClientCode)

SELECT DISTINCT dim_matter_header_current.master_client_code+'-'+dim_matter_header_current.master_matter_number AS [Client/Matter Number]
	, dim_matter_header_current.matter_description AS [Matter Description]
	, dim_matter_header_current.matter_owner_full_name AS [Case Manager]
	, dim_fed_hierarchy_history.hierarchylevel4hist AS [Team]
	, dim_fed_hierarchy_history.hierarchylevel3hist AS [Department]
	, ISNULL(dim_matter_header_current.client_group_name, dim_matter_header_current.client_name) AS [Client Group/Name]
	, dim_key_dates.description AS [Key Date Description]
	, dim_key_dates.key_date AS [Key Date]

FROM red_dw.dbo.dim_key_dates
LEFT OUTER JOIN red_dw.dbo.fact_dimension_main
ON fact_dimension_main.dim_matter_header_curr_key = dim_key_dates.dim_matter_header_curr_key
LEFT OUTER JOIN red_dw.dbo.dim_matter_header_current
ON dim_matter_header_current.dim_matter_header_curr_key = fact_dimension_main.dim_matter_header_curr_key
LEFT OUTER JOIN red_dw.dbo.dim_fed_hierarchy_history
ON dim_fed_hierarchy_history.dim_fed_hierarchy_history_key = fact_dimension_main.dim_fed_hierarchy_history_key

INNER JOIN #Department AS Department ON Department.ListValue COLLATE DATABASE_DEFAULT = dim_fed_hierarchy_history.hierarchylevel3hist
INNER JOIN #Team AS Team ON Team.ListValue COLLATE DATABASE_DEFAULT = dim_fed_hierarchy_history.hierarchylevel4hist
INNER JOIN #CaseManager AS CaseManager ON CaseManager.ListValue COLLATE DATABASE_DEFAULT = dim_matter_header_current.matter_owner_full_name
INNER JOIN #ClientGroup AS ClientGroup ON ClientGroup.ListValue COLLATE DATABASE_DEFAULT = ISNULL(dim_matter_header_current.client_group_name, dim_matter_header_current.client_name)
INNER JOIN #ClientCode AS ClientCode ON ClientCode.ListValue COLLATE DATABASE_DEFAULT = dim_matter_header_current.master_client_code

WHERE dim_matter_header_current.reporting_exclusions=0
AND dim_matter_header_current.date_closed_case_management IS NULL 
AND dim_key_dates.key_date>=@DateFrom
AND dim_key_dates.key_date<=@DateTo
AND dim_key_dates.is_active=1
AND dim_key_dates.type IN ('RETAINEREND'
,'CHRONOL'
,'DRALEASELAN'
,'WITEVIDENCE'
,'GRANTINHERIT'
,'PRELIMHEAR'
,'CASESUMM'
,'OPTIONS'
,'ACKNOSERV'
,'AVAILABILITY'
,'RETURN'
,'CLAIMP36EXP'
,'CERTRESPONSE'
,'2MSECTION26'
,'DEFBHRR'
,'ACASCONCIL'
,'TRIAL'
,'INFAPP'
,'PRECH'
,'ACTIONSTAYED'
,'LOCUSREP'
,'DEFMEDEX'
,'POSSPROCEE'
,'LIMITATION'
,'APPVERDICT'
,'LISTWIT'
,'AQDQ'
,'COURTHEARING'
,'DISC'
,'COURTSTAY'
,'MEDREP'
,'JOBDESC'
,'SUPPMEDREPORT'
,'COMPPURCHASE'
,'AMENDCLAIM'
,'ELAPSEDAYS'
,'AQDQ'
,'PLANDATE'
,'STAMPDUTY'
,'DEFMEDREP'
,'SCHLOSS'
,'BANK'
,'NHSSTAFF'
,'DISHEARING'
,'ADVISEZURICH'
,'MOTWITHDRAW'
,'OS1EXP'
,'NHSLAP36'
,'NHSLASOLREP'
,'E14RESERVE'
,'QUESNONMED'
,'STANDARDLIMITV2'
,'HEARING'
,'OBTAININFOHEAR'
,'CLIENTTRAIN'
,'QNONEXP'
,'CRPEXPIRY'
,'STAGE3APP'
,'COURTCOSTS'
,'ICORESP'
,'LODGEVALUATION'
,'SERVICEBUNDLE'
,'UPDATECOURT'
,'COUNTERSCHLOSS'
,'CLAIMANTDAM'
,'DEFNONMEDREP'
,'STUTPINTERVIEW'
,'COMPCOURTORDER'
,'FAILUNAVAIL'
,'STAGE3PAPER'
,'EXPIRY27'
,'STAGE1EVH'
,'PART36'
,'LISTINGAPP'
,'PANEL'
,'COMPIMPROV'
,'JOINSETT'
,'PRELIMHEARAG'
,'REPLYPOD'
,'RESPFURTHERINFO'
,'BRCONTEMP'
,'RECLODGE'
,'FILEXPJOINSTAT'
,'DEBATE'
,'REVUNDER'
,'PRETRIALMEET'
,'LANDREG'
,'CHQCLAIMANT'
,'UNIINTERVIEW'
,'ICOREG'
,'PRETRIALMIN'
,'STANDARDLIMITV2'
,'RESADVICE'
,'CLPAYHEAR'
,'TRIALWINDOW'
,'FIRSTDIR'
,'SERVEUM'
,'BRCONT'
,'ACASCOUNCIL'
,'LISTINGQUES'
,'STAGE2EVH'
,'IDENTIFY'
,'REPLYMEDEXP'
,'LANDCHARG'
,'INTERLOC'
,'UNFAIRDISMISS'
,'CAPITASLADATE'
,'SERVICEOFCLAIM'
,'INSTNONMEDEXP'
,'RESREQF&BP'
,'94A'
,'COUNTERSCH'
,'REAMENDRALEA'
,'DEFENCESDUE'
,'REPLYDEFCC'
,'PAYCLAIMSOLS'
,'CRUAPPEAL'
,'CLABHRR'
,'DEATHIHT'
,'TIMENOTICEAPP'
,'LANRETSCH'
,'NHSLAEXPREP'
,'FILEANSWERPET'
,'POINTSDISP'
,'CLAPAYHEAR'
,'PRETRIALREP'
,'COUNTERSCHLOSS'
,'MORTGAGE'
,'RENEWAL'
,'TRIALBUNDLE'
,'JOINEDMIB'
,'RTM'
,'POINTSDISPUTE'
,'EXPSECTION26'
,'10YRANNI'
,'REPLYQUES'
,'PREACTIONDISC'
,'APPDECREE'
,'DCPDEFDQ'
,'APPSJUSTMENT'
,'MEDREC'
,'NHSLAPROC'
,'INQUEST'
,'NHSRSCHED5'
,'COSTSCHQ'
,'LDADJUST'
,'APPHEARING'
,'WITLISTDEF'
,'UPDATEDSCHOFLOS'
,'AGREEISSUES'
,'REFCDR'
,'REQEXTREASONS'
,'BREAK'
,'JOINTAGSTAT'
,'UNLESSORDERDEF'
,'DCPAOS'
,'BILLNHSLA'
,'EXPERTAPPOINT'
,'DAMAGECHQ'
,'PREINQREVHEAR'
,'DISCJOINMED'
,'MORTGAGE'
,'DISHEARING'
,'REPLIESQSNONMED'
,'DEFENCE'
,'REQF&BP'
,'SCHDISPLEASE'
,'PERPETPERIOD'
,'POCDUE'
,'SUBJECTACCESS'
,'EXCHMEDREP'
,'RETAINEREND'
,'CRUAPP'
,'EXCHSKELETON'
,'LASTDATEPART36'
,'SDLTNOTPAYDUE'
,'BNKRPTSRCHEXP'
,'DEFBILLCOSTS'
,'DETAILASSESHEAR'
,'SECTION26'
,'STANDARDLIMIT'
,'CASECALL'
,'DISCNONMED'
,'COMWEIPREFORM'
,'PPODUE'
,'CASEMANDISC'
,'SCHEDCOST'
,'ET1DUE'
,'PROVJOBDESC'
,'FINDISPRESS'
,'P18RESP'
,'STAGE3ORAL'
,'POSSTATE'
,'NID'
,'EXPIRYBREAK'
,'STRATDEVCALL'
,'COURTAPPEAL'
,'ATEPREMIUM'
,'INJHEARING'
,'SERVPROV'
,'PROOF'
,'CAPITASLAREPORT'
,'PORTRESPONSE'
,'PRODUCT'
,'EXCHEXPREP'
,'APPSJUSTMENT'
,'PRECH'
,'COMPLETION'
,'REVIEWRESERVE'
,'APPJUDICIAL'
,'ADJSUMMONS'
,'PART8PROC'
,'PURLODGE'
,'EXPLANDREGPP'
,'BENEFAGEMAJOR'
,'DEFPAY'
,'VARYORDER'
,'SMALLCLAIM'
,'CMC'
,'CLAIMANTSCH'
,'ADJUSTPERIOD'
,'ACKNOSERV'
,'REVIEWCOSTSRES'
,'EXPIRYSTAY'
,'EARLYCON'
,'PAYSTAGE1FEE'
,'AMENTENLEASE'
,'94A'
,'EXPSECTION25'
,'BAIL'
,'ISSUEPAD'
,'JOINTDISCNONMED'
,'EXCHNONMEDREP'
,'INSPECTDOCS'
,'STANDARDLIMIT'
,'REVIEWCOSSTSEST'
,'DIRPROPLIT'
,'ANNUALREN'
,'EXCHWITSTAT'
,'FIRSTAPP'
,'CANCLANREG'
,'LIMCONTPRO'
,'KDTRIALDATELIT'
,'NHSLATRIAL'
,'DATEDETERMIN'
,'UNDERTAKE'
,'PRETRIALCHECK'
,'ET3'
,'FIRSTCALL'
,'DSARRESP'
,'MEDIATION'
,'IPDIPERIODEND'
,'TRIALFEE'
,'CLAIMCOSTS'
,'DISCRIM'
,'PART8ACK'
,'DEFP36OFFER'
,'COMPFDADIRECT'
,'COSTSBUDGE'
,'QUESMEDEXP'
,'CONF'
,'RULE22'
,'TPNOTICE'
,'LIMITATIONV2'
,'JOINTDISCMED'
,'6YEARLIM'
,'LETTERRESP'
,'WITAVAILAB'
,'PROVASSES'
,'APPEALIMPROV'
,'DISCBHRR'
,'MEETEXPERT'
,'LEASEEXP'
,'DATEOFEVICTION'
,'COURTPROCOSBUD'
,'ACCUMPERIODEND'
,'TRIALWARNED'
,'JOINTSTATEMED'
,'PROTRESP'
,'PROCOURT'
,'PACE'
,'NOTICEAPPEAL'
,'PRETREVIEW'
,'WARNEDPERIOD'
,'REGCOMPHOUSE'
,'ISSUEPROC'
,'REPORTCLIENT'
,'INSTMEDEXP'
,'PROTOCOL'
,'OS2EXP'
,'STATENONMED'
,'PURSVAL'
,'APPEALHEAR'
,'DEATHREP'
,'LOCDUE'
,'ADLIABILITY'
)

ORDER BY dim_key_dates.key_date ASC 
  
END
GO
