CREATE TABLE [dbo].[timekeeperimports]
(
[timekeeperindex] [int] NULL,
[Entity] [int] NULL,
[TRE_User] [varchar] (40) COLLATE Latin1_General_CI_AS NULL,
[payrollid] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[firstname] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[surname] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[knownas] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[name] [nvarchar] (101) COLLATE Latin1_General_BIN NULL,
[DOB] [datetime] NULL,
[prefix] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[gender] [varchar] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[email] [nvarchar] (320) COLLATE Latin1_General_BIN NULL,
[phonenumber] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[username] [nvarchar] (54) COLLATE Latin1_General_BIN NULL,
[startdate] [datetime] NULL,
[office] [nvarchar] (16) COLLATE Latin1_General_CI_AI NULL,
[officename] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[address] [int] NULL,
[sitetype] [nvarchar] (16) COLLATE Latin1_General_CI_AI NULL,
[businessline] [nvarchar] (16) COLLATE Latin1_General_CI_AI NULL,
[team] [nvarchar] (16) COLLATE Latin1_General_CI_AI NULL,
[jobrole] [nvarchar] (16) COLLATE Latin1_General_CI_AI NULL,
[hrtitle] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[payrollid_BCM] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[ratetype] [varchar] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[defaultrate] [int] NOT NULL,
[tkrtype] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[userstatusid] [int] NOT NULL,
[userstatus] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[leaverdate] [datetime] NULL,
[dss_update_time] [datetime] NULL
) ON [PRIMARY]
GO
