CREATE TABLE [dbo].['Omniscope data']
(
[MS Only] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Weightmans References] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Ref to link] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Matter Description] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Case Manager] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Case Manager Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Team Manager] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Team Manager (non-cascade)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Supervisor Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Bcm] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Office (Case Manager)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Office (Case Plan)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Team] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Matter Category] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Matter Category Code] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Division] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Department] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Work Type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Work Type Code] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Worktype Group] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Client Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Client Group Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Client Sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insurer Client Reference] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Clients Claim Handler] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insurer Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insured Client Reference] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insured Client Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insured Department] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insured Department Depot Postcode] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insured Sector] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Case Opened] [datetime] NULL,
[Date Case Closed] [datetime] NULL,
[Converge Date Closed] [datetime] NULL,
[Present Position] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Converge Claim Status] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Initial Report Sent] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date initial report sent] [datetime] NULL,
[Date Instructions Received] [datetime] NULL,
[Status_On_Instruction] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Referral Reason] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Proceedings Issued] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Proceedings Issued] [datetime] NULL,
[Reason for Litigation] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Sub Reason Litigation] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Court Reference] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Court Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Track] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Suspicion of Fraud?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Initial Fraud Type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Current Fraud Type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Credit Hire] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Credit Hire Organisation] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Number of Defendants] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Number of Claimants] [float] NULL,
[Does Claimant Have Personal Injury Claim?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Description of Injury] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Litigation / Regulatory] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Issue on Liability] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Delegated] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Fixed Fee] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Fixed Fee Amount] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Fee Arrangement] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Percentage Completion] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Linked File?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Lead Follow] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Lead File Matter Number] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Associated Matter Numbers] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date CNF sent] [datetime] NULL,
[MoJ stage] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[MOJ Apply] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Who Dropped the Claim out of Portal?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Incident Date] [datetime] NULL,
[Incident Location] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant's Solicitor] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant's Postcode] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Has Claimant got a CFA?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[CFA entered into before 1 April 2013] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Total Reserve Initial] [float] NULL,
[Total Reserve Current] [float] NULL,
[Converge Disease Reserve (net)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Damages Reserve Initial (based on first Current Reserve)] [float] NULL,
[Damages Reserve Initial (based on detail TRA077)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Damages Reserve Current] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Hire Claimed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant Costs Reserve Initial] [float] NULL,
[Claimant Costs Reserve Current] [float] NULL,
[Defence Costs Reserve Initial] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Defence Costs Reserve Current] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Other Defendants Costs Reserve Initial] [float] NULL,
[Other Defendants Costs Reserve Current] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Disease Total Estimated Settlement Value] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[% of Client's Liability Agreed Prior to Instruction] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[% of Contributory Negligence Agreed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[% of Client's Liability Awarded/Agreed Post insts/applied] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Outcome of Case] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date of Trial] [datetime] NULL,
[Date Claim Concluded] [datetime] NULL,
[Damages Paid by Client] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Outsource Damages Paid (WPS278+WPS279+WPS281)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Personal Injury Paid] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Hire Paid] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Total Settlement Value of the Claim Paid by all the Parties] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[NHS charges paid by all parties] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[CRU paid by all parties] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Referral to Costs Unit] [datetime] NULL,
[Date Costs Settled] [datetime] NULL,
[Date Settlement Form sent to Zurich] [datetime] NULL,
[Total third party costs claimed (the sum of TRA094+NMI599+NMI600] [float] NULL,
[Claimants Total Costs Claimed against Client] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Total third party costs paid (sum of TRA072+NMI143+NMI379)] [float] NULL,
[Outsource Claimant's Costs] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant's Total Costs Paid by Client] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Detailed Assessment Costs Claimed by Claimant] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Detailed Assessment Costs Paid] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Costs Claimed by another Defendant] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Costs Paid to Another Defendant] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant's Total Costs Paid by all Parties] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Are we Pursuing a Recovery?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Recovery Concluded] [datetime] NULL,
[Recovery Claimant's Damages via Third Party Contribution] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Recovery Claimant's Costs via Third Party Contribution] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Recovery Claimant's (Our Client) Damages] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Recovery Defence Costs from Claimant] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Recovery Defence Costs via Third Party Contribution] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Total Recovery (sum of NMI112+NMI135+NMI136+NMI137)] [float] NULL,
[Outsource Recovery Paid] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Total Amount Billed] [float] NULL,
[Profit Costs Billed] [float] NULL,
[Disbursements Billed] [float] NULL,
[VAT Billed] [float] NULL,
[Wip] [float] NULL,
[Unbilled Disbursements] [float] NULL,
[Client Account Balance of Matter] [float] NULL,
[Last Bill Date] [datetime] NULL,
[Total Chargeable Hours] [float] NULL,
[Total Non-Partner Hours Recorded] [float] NULL,
[Total Partner Hours Recorded] [float] NULL,
[Date of Last Time Posting] [datetime] NULL,
[Profit Costs Billed 13/14] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Profit Costs Billed 14/15] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Profit Costs Billed 15/16] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Profit Costs Billed 16/17] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Profit Costs Billed 17/18] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Total Live Days Elapsed] [float] NULL,
[Days from Date opened in FED to Date Costs Settled] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Repudiated / Settled?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Instruction Type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Fraud Type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Minutes Recorded] [float] NULL,
[Weightmans Reference Trimmed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Damages Banding] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Weightmans Reference] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Unpaid Bill Balance] [float] NULL,
[PI Reserve Initial] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PI Reserve Current] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[General Damages Paid] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Re-opened] [datetime] NULL,
[Name of Costs Negotiators] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant's solicitor's base costs claimed + VAT] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant's solicitor's base costs paid + VAT] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimant_Costs_Reserve_Current] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimants_Total_Costs_Paid_By_All_Parties] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Credit Hire Organisation Detail] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Grade] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Leaver?] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Time_Billed] [float] NULL,
[Tp_Total_Costs_Claimed_All_Parties] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[HoursBilled2016/2017] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[HoursBilled2017/2018] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Damages_Interims] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Interim_Damages_Paid_By_Client_Preinstruction] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Total Associate Hours Recorded] [float] NULL,
[Total Other Hours Recorded] [float] NULL,
[Total Paralegal Hours Recorded] [float] NULL,
[Total Partner/Consultant Hours Recorded] [float] NULL,
[Total Solicitor/LegalExec Hours Recorded] [float] NULL,
[Total Trainee Hours Recorded] [float] NULL
) ON [PRIMARY]
GO
