CREATE TABLE [dbo].[MSPROD_dbPrecedents_Data]
(
[PrecID] [bigint] NOT NULL,
[brID] [int] NULL,
[PrecTitle] [nvarchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[PrecType] [nvarchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[PrecLibrary] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecCategory] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecSubCategory] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecLanguage] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[PrecText] [bit] NOT NULL,
[PrecDesc] [nvarchar] (100) COLLATE Latin1_General_CI_AS NOT NULL,
[PrecPubName] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PrecAddressee] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecAssocType] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecAutoName] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PrecPath] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[PrecLocation] [smallint] NULL,
[PrecDirID] [smallint] NULL,
[PrecReminder] [bit] NOT NULL,
[PrecNoOfDays] [smallint] NOT NULL,
[PrecRemComment] [nvarchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PrecReviewNoOfDays] [smallint] NULL,
[PrecTimeRecUnits] [int] NOT NULL,
[PrecTimeRecDesc] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PrecTimeRecCode] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[precTimeRecInCode] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecInternalProcess] [bit] NOT NULL,
[PrecProgType] [smallint] NULL,
[PrecMS] [smallint] NOT NULL,
[PrecMoveMS] [bit] NOT NULL,
[PrecMSChangePrompt] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecMSNote] [ntext] COLLATE Latin1_General_CI_AS NULL,
[PrecMSAuto] [bit] NOT NULL,
[PrecMSCode] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecGlossary] [ntext] COLLATE Latin1_General_CI_AS NULL,
[PrecSMSMessage] [nvarchar] (150) COLLATE Latin1_General_CI_AS NULL,
[PrecUpdateSQL] [ntext] COLLATE Latin1_General_CI_AS NULL,
[PrecMultiPrec] [bit] NOT NULL,
[PrecPassword] [nvarchar] (25) COLLATE Latin1_General_CI_AS NULL,
[PrecPasswordHint] [nvarchar] (75) COLLATE Latin1_General_CI_AS NULL,
[PrecScript] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[PrecPreview] [ntext] COLLATE Latin1_General_CI_AS NULL,
[precExtension] [nvarchar] (15) COLLATE Latin1_General_CI_AS NULL,
[precDirection] [bit] NOT NULL,
[precXML] [ntext] COLLATE Latin1_General_CI_AS NOT NULL,
[Created] [smalldatetime] NOT NULL,
[CreatedBy] [int] NULL,
[Updated] [smalldatetime] NULL,
[UpdatedBy] [int] NULL,
[precDeleted] [bit] NOT NULL,
[precRetain] [smalldatetime] NULL,
[rowguid] [uniqueidentifier] NOT NULL,
[precCurrentVersion] [uniqueidentifier] NULL,
[precChecksum] [varchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
