CREATE TABLE [ss].[GeneralDataFile]
(
[Weightmans Reference] [varchar] (17) COLLATE Latin1_General_BIN NULL,
[Client Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter Number] [char] (8) COLLATE Latin1_General_BIN NULL,
[Client Code Trimmed] [varchar] (8000) COLLATE Latin1_General_BIN NULL,
[Matter Number Trimmed] [varchar] (8000) COLLATE Latin1_General_BIN NULL,
[Weightmans Reference Trimmmed] [varchar] (8000) COLLATE Latin1_General_BIN NULL,
[Mattersphere Client Code] [nvarchar] (4000) COLLATE Latin1_General_BIN NULL,
[Mattersphere Matter Number] [nvarchar] (4000) COLLATE Latin1_General_BIN NULL,
[Mattersphere Weightmans Reference] [nvarchar] (4000) COLLATE Latin1_General_BIN NULL,
[Matter Description] [varchar] (200) COLLATE Latin1_General_BIN NULL,
[Date Case Opened] [datetime] NULL,
[OpenedCaseDate_Finance] [datetime] NULL,
[Date Case Closed] [datetime] NULL,
[Open/Closed Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Open/Closed Case Status] [varchar] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[Date Instructions Received] [datetime] NULL,
[Date Claim Concluded] [datetime] NULL,
[Claim Concluded Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Outcome of Case] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Case Manager Name] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[Case Manager] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[FTE] [numeric] (18, 16) NULL,
[Team Manager] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[BCM Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[BCM] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[Business Line] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Practice Area] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Branch Name] [char] (40) COLLATE Latin1_General_BIN NULL,
[Department Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[Department] [char] (40) COLLATE Latin1_General_BIN NULL,
[Work Type Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[Work Type] [char] (40) COLLATE Latin1_General_BIN NULL,
[Client Group Name] [varchar] (40) COLLATE Latin1_General_BIN NULL,
[Client Name] [char] (80) COLLATE Latin1_General_BIN NULL,
[Client Sector] [char] (40) COLLATE Latin1_General_BIN NULL,
[Segment] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Client Sub-sector] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Claimant's Solicitor] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Claimant's Solicitors Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Name of Claimant's Firm] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[Claimant Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Claimant's DOB] [datetime] NULL,
[Claimant's Postcode] [char] (15) COLLATE Latin1_General_BIN NULL,
[Number of Claimants] [numeric] (13, 2) NULL,
[Policy Holder Name] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insurer Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Insurer Client Reference] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Insured Department] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insured Department Depot Postcode] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insured Client Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Insured Client Reference] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Court Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Court Reference] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Present Position] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Track] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Suspicion of Fraud?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Referral Reason] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Fixed Fee] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Proceedings Issued] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Proceedings Issued] [datetime] NULL,
[Accident Location] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Incident Date] [datetime] NULL,
[Incident Location] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Type of Injury] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Injury Type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Description of Injury] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Engineer Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Credit Hire] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Credit Hire Organisation] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Credit Hire Organisation Detail] [varchar] (500) COLLATE Latin1_General_BIN NULL,
[Hire Start Date] [datetime] NULL,
[Hire End Date] [datetime] NULL,
[Lead Follow] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Linked File?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Lead File?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Lead File Matter Number] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Associated Matter Numbers] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Work Referral?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Fraud Status] [datetime] NULL,
[Weightmans Comments] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date of Current Estimate to Complete Retainer] [datetime] NULL,
[Date Letter of Claim] [datetime] NULL,
[Date Initial Report Sent] [datetime] NULL,
[Date of Pre-Trial Report] [datetime] NULL,
[Date of Trial] [datetime] NULL,
[Trial Window] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Start of Trial Window] [datetime] NULL,
[Date End Of Trial Window] [datetime] NULL,
[Infant Approval] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[MoJ stage] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Reason for Instruction] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Sub Report] [datetime] NULL,
[Closure Report] [datetime] NULL,
[Liability Issue] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Delegated] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Live Claim] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Live Case Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Litigated] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Converge Claim Status] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Converge Closure Reason] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Claimants Costs Received] [datetime] NULL,
[Date Costs Settled] [datetime] NULL,
[Elapsed Days Live Files] [int] NULL,
[Elapsed Days Conclusion] [int] NULL,
[Interim Costs Payments] [numeric] (13, 2) NULL,
[Fraud Savings] [numeric] (13, 2) NULL,
[Case Classification] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Converge Date Closed] [datetime] NULL,
[status_on_instruction] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[reason_for_litigation] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Level] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Post ID] [nvarchar] (200) COLLATE Latin1_General_BIN NULL,
[Payroll ID] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Office] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Grade] [nvarchar] (200) COLLATE Latin1_General_BIN NULL,
[Total MI Exceptions] [int] NULL,
[Total Critical MI Exceptions] [bit] NULL,
[final_bill_date_grp] [datetime] NULL,
[Last Bill Date] [datetime] NULL,
[Date of Final Bill] [datetime] NULL,
[Leaver?] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Date of Last Time Posting] [datetime] NULL,
[Client Account Balance of Matter] [numeric] (13, 2) NULL,
[Number of Records] [int] NOT NULL,
[Financial Quarter Opened] [varchar] (34) COLLATE Latin1_General_CI_AS NULL,
[Financial Year Opened] [varchar] (61) COLLATE Latin1_General_CI_AS NULL,
[Financial Quarter Closed] [varchar] (34) COLLATE Latin1_General_CI_AS NULL,
[Financial Year Closed] [varchar] (61) COLLATE Latin1_General_CI_AS NULL,
[Elapsed Days Live Bandings] [varchar] (7) COLLATE Latin1_General_CI_AS NULL,
[Number of Live Instructions] [int] NOT NULL,
[Week Commencing] [datetime] NULL,
[Week Number] [varchar] (7) COLLATE Latin1_General_CI_AS NULL,
[GetDate 4 Years] [datetime] NULL,
[Worktype Group] [varchar] (17) COLLATE Latin1_General_CI_AS NOT NULL,
[YearPeriod_MMYY] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[PeriodType] [int] NOT NULL,
[Calendar Quarter Received] [varchar] (4) COLLATE Latin1_General_CI_AS NULL,
[Calendar Quarter Opened] [varchar] (4) COLLATE Latin1_General_CI_AS NULL,
[Status] [varchar] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[All Work Types] [varchar] (8000) COLLATE Latin1_General_BIN NULL,
[Date Received/Opened] [datetime] NULL,
[Minutes Recorded] [numeric] (38, 2) NULL,
[Hours Recorded] [numeric] (38, 6) NULL,
[Sum Total of Concluded Matters] [int] NOT NULL,
[Conclusion Days] [int] NULL,
[Elapsed Days to Costs Settlement] [int] NULL,
[Elapsed Days to Outcome] [int] NULL,
[Filestatus] [varchar] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[Instruction Type] [char] (60) COLLATE Latin1_General_BIN NULL,
[Rolling 12 Months Concluded] [int] NOT NULL,
[Rolling 12 Months Opened] [int] NOT NULL,
[Repudiation - outcome] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Time Recorded (Banded)] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[Free 12 mins Used?] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Chargeable Time] [numeric] (38, 2) NULL,
[Legal Spend exc (VAT)] [numeric] (38, 6) NULL,
[Total Partner Hours Recorded] [numeric] (38, 6) NULL,
[Total Non-Partner Hours Recorded] [numeric] (38, 6) NULL,
[Total Partner/Consultant Hours Recorded] [numeric] (38, 6) NULL,
[Total Associate Hours Recorded] [numeric] (38, 6) NULL,
[Total Solicitor/LegalExec Hours Recorded] [numeric] (38, 6) NULL,
[Total Paralegal Hours Recorded] [numeric] (38, 6) NULL,
[Total Trainee Hours Recorded] [numeric] (38, 6) NULL,
[Total Other Hours Recorded] [numeric] (38, 6) NULL,
[Litigation / Regulatory] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[Fraud Type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Days from Date receipt of Claimant's Costs to Date Costs Settled] [int] NULL,
[Days from Date opened in FED to date of last bill on file (closed matters)] [int] NULL,
[Days from Date opened in FED to Converge Date Closed] [int] NULL,
[Days from Date opened in FED to Date Settlement Form Sent to Zurich] [int] NULL,
[Whitbread Year Period] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Litigated/Proceedings Issued] [varchar] (13) COLLATE Latin1_General_CI_AS NOT NULL,
[Status - Disease] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[Track - Disease] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[PP Description] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[Optimum Case Level] [numeric] (22, 0) NULL,
[Fraud Optimum Case Level] [numeric] (21, 0) NULL,
[Credit Hire Optimum Case Level] [numeric] (21, 0) NULL,
[Claimant's Solicitors Firm] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[FY Date Claim Concluded] [varchar] (61) COLLATE Latin1_General_CI_AS NULL,
[FY Date Costs Settled] [varchar] (61) COLLATE Latin1_General_CI_AS NULL,
[FY Date Instructions Received] [varchar] (61) COLLATE Latin1_General_CI_AS NULL,
[time_billed] [numeric] (17, 6) NULL
) ON [PRIMARY]
GO
