CREATE TABLE [CIS].[MIUSLASnapshotData]
(
[case_id] [int] NOT NULL,
[Client] [varchar] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[Matter] [varchar] (8) COLLATE Latin1_General_CI_AS NOT NULL,
[CIS Reference] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Date Closed in FED] [date] NULL,
[Date Opened in FED] [date] NOT NULL,
[Insured Name] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[FeeEarner] [varchar] (88) COLLATE Latin1_General_CI_AS NULL,
[ID] [varchar] (8000) COLLATE Latin1_General_CI_AS NULL,
[No. of Claimants] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[RTA Date] [date] NULL,
[Date Received] [date] NULL,
[Month Instructions Received] [char] (3) COLLATE Latin1_General_CI_AS NULL,
[Last 12 Months] [datetime] NULL,
[Elapsed Days] [int] NULL,
[Fixed Fee] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[GuidNumber] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Date Closed/declared dormant] [datetime] NULL,
[BlankColumn] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[Date MI Updated] [datetime] NULL,
[Date re-opened] [date] NULL,
[Estimated Final Fee] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Status] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Outcome] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Policyholder Involvement] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Fraud Type] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[MI Reserve] [money] NULL,
[BlankColumn2] [varchar] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[Date Pleadings Issued] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Paid prior to instruction] [money] NULL,
[Settlement Value] [decimal] (19, 4) NULL,
[Fees] [decimal] (19, 4) NULL,
[Net Savings] [decimal] (19, 4) NULL,
[Potential Recovery] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Audit] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Narrative] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Gunum] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[date_closed] [date] NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Weightmans Fee Earner] [varchar] (81) COLLATE Latin1_General_CI_AS NULL,
[FedStatus] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
[Master date closed/ dormant] [datetime] NULL,
[Master date MI updated] [datetime] NULL,
[Master Status] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Master Outcome] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Master settlement value] [decimal] (13, 2) NULL,
[Master fees] [decimal] (13, 2) NULL,
[Master net savings] [decimal] (13, 2) NULL,
[ReportingTab] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[FeeEarnerCode] [varchar] (4) COLLATE Latin1_General_CI_AS NOT NULL,
[SAP_Open] [varchar] (9) COLLATE Latin1_General_CI_AS NOT NULL,
[WIPBal] [decimal] (13, 2) NULL,
[TotalProfitCostsBilled] [money] NULL,
[ProfitCostsVAT] [money] NULL,
[SAPClosedDate] [smalldatetime] NULL,
[Date Claim Concluded] [datetime] NULL,
[Month Claim Concluded] [char] (3) COLLATE Latin1_General_CI_AS NULL,
[Year Claim Concluded] [int] NULL,
[Incident Location] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Claimant Postcode] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[Present Position] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Date of repudiation] [date] NULL,
[Date Proceedings Issued] [date] NULL,
[Recipt To Desition on Whether to Repudiate] [int] NULL,
[Recipt To Desition on Whether to Repudiate Volume] [int] NOT NULL,
[Recept to 50% dormant Volume] [int] NULL,
[Recept to 50% dormant Elapsed] [int] NULL,
[Recept to 95% dormant Volume] [int] NULL,
[Recept to 95% dormant Elapsed] [int] NULL,
[Recept to File Closed Volume] [int] NULL,
[Recept to File Closed Elapsed] [int] NULL,
[Litigation] [varchar] (13) COLLATE Latin1_General_CI_AS NOT NULL,
[Year Period] [int] NULL,
[Period] [varchar] (11) COLLATE Latin1_General_CI_AS NULL,
[Number opened claims] [int] NULL,
[Total Number of Claims In Litigation] [int] NULL,
[Number of Litigated Claims Concluded] [int] NULL,
[Number of Claims Entering Litigation] [int] NULL,
[InsertedDate] [datetime] NULL,
[Damages Reserve Held LeadLinked] [decimal] (19, 4) NULL,
[Opponents Costs Reserve Held LeadLinked] [decimal] (19, 4) NULL,
[Defence Costs Reserve Held LeadLinked] [decimal] (19, 4) NULL,
[ABI Fraud Proven] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Is this a fraud ring] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Underwriting Referral Made] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Pre Lit Fees] [decimal] (19, 4) NULL,
[Litigated Fees] [decimal] (19, 4) NULL,
[Disbursements] [decimal] (19, 4) NULL
) ON [PRIMARY]
GO
