CREATE TABLE [converge].[ves_datafix]
(
[Client] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter] [char] (8) COLLATE Latin1_General_BIN NULL,
[TransactionNumber] [nvarchar] (64) COLLATE Latin1_General_CI_AI NULL,
[TransactionDescription] [nvarchar] (64) COLLATE Latin1_General_CI_AI NULL,
[TransactionType] [nvarchar] (16) COLLATE Latin1_General_CI_AI NULL,
[TransactionTypeDescription] [nvarchar] (64) COLLATE Latin1_General_CI_AI NULL,
[TransactionDate] [datetime] NULL,
[PostingDate] [datetime] NULL,
[SystemDate] [datetime] NULL,
[BankCode] [nvarchar] (64) COLLATE Latin1_General_CI_AI NULL,
[PaymentNumber] [char] (60) COLLATE Latin1_General_BIN NULL,
[RecoveryNumber] [char] (60) COLLATE Latin1_General_BIN NULL,
[ArtiionSequenceNumber] [nvarchar] (64) COLLATE Latin1_General_CI_AI NULL,
[ChequeAmount] [decimal] (16, 2) NOT NULL,
[PaymentGross] [decimal] (18, 2) NOT NULL,
[PaymentNet] [decimal] (15, 2) NOT NULL,
[PaymentVAT] [decimal] (15, 2) NOT NULL,
[RecoveryAmount] [decimal] (13, 2) NOT NULL,
[PaymentToWhom] [char] (60) COLLATE Latin1_General_BIN NULL,
[InvoiceNumber] [char] (60) COLLATE Latin1_General_BIN NULL,
[RecoveryFromWhom] [char] (60) COLLATE Latin1_General_BIN NULL,
[IncidentDate] [datetime] NULL,
[PolicyType] [char] (60) COLLATE Latin1_General_BIN NULL,
[AmountType] [nvarchar] (64) COLLATE Latin1_General_CI_AI NULL,
[transaction_type_group] [varchar] (12) COLLATE Latin1_General_CI_AS NULL,
[reference_number] [nvarchar] (64) COLLATE Latin1_General_CI_AI NULL,
[PaymentNotes1] [char] (60) COLLATE Latin1_General_BIN NULL,
[PaymentType] [char] (60) COLLATE Latin1_General_BIN NULL,
[Fees] [int] NOT NULL,
[tr_client] [char] (8) COLLATE Latin1_General_BIN NULL,
[tr_matter] [char] (8) COLLATE Latin1_General_BIN NULL,
[tr_trrefn] [char] (8) COLLATE Latin1_General_BIN NULL,
[tr_amount] [numeric] (13, 2) NULL,
[tr_trdesc] [char] (40) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
