CREATE TABLE [dbo].[EWICClaimsTeamData]
(
[ClaimNumber] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ClaimHandler] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Category/type of claim ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Policy Wording] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[New / Rectification Work] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Cunningham Lindsay (Previous Contractor)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Possible Hardship Considerations] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Hardship Comments] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Media / Government agency involvement] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Additional Claims Background Comments / Concerns] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[FSCS qualifying test] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ClaimComplexity] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claim Phase] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Works Ongoing - Status] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[COVID Considerations] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Detail of Investigations Required] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Experts Used (To be Used)] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Next steps/next action needed ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Phase 1 Pre-Liability acceptance or Phase 2 Reinstatement] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Priority] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Waking Watch or Fire Notice issued] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Brief Note on Reason For Priority Rating] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Quick Win if Loss Adjuster or Expert Instructed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Next review date] [datetime] NULL,
[Issues Prevent further Progress] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Issues Preventing Progress Comments] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Cunningham Lindsay Comment] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Recovery Status] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FSCS Eligibility Confirmed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[BAU and Claim Progressing] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Initial Potential Estimate] [float] NULL,
[Refreshed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
