CREATE TABLE [dbo].[ClaimsSLAComplianceTable]
(
[Client Name] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[client_group_name] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[master_client_code] [nvarchar] (12) COLLATE Latin1_General_BIN NULL,
[master_matter_number] [nvarchar] (20) COLLATE Latin1_General_BIN NULL,
[Client Code] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter Number] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter Description] [varchar] (200) COLLATE Latin1_General_BIN NULL,
[Matter Owner] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[employeeid] [char] (36) COLLATE Latin1_General_BIN NULL,
[fee_earner_code] [nvarchar] (30) COLLATE Latin1_General_BIN NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Department] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Status] [varchar] (6) COLLATE Latin1_General_CI_AS NOT NULL,
[Mattersphere Weightmans Reference] [nvarchar] (33) COLLATE Latin1_General_BIN NULL,
[Present Position] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[NHS Instruction Type (N1001 Only)] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Opened] [datetime] NULL,
[Date Closed] [datetime] NULL,
[Date Instructions Received] [datetime] NULL,
[Days to File Opened from Date Instructions Received] [decimal] (20, 2) NULL,
[Date Initial Report Sent] [datetime] NULL,
[Do Clients Require an Initial Report?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Receipt of File Papers] [datetime] NULL,
[Have we had an Extension?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Initial Report Due (if extended)] [datetime] NULL,
[Inverted Date Initial Report Due] [datetime] NULL,
[Initial Report Rules] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[inverted_initial_rule] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Date Subsequent SLA Report Sent] [datetime] NULL,
[Days without Subsequent Report] [decimal] (20, 2) NULL,
[Number of Files] [int] NOT NULL,
[avglifecycle] [numeric] (13, 2) NULL,
[inverted_avglifecycle] [int] NULL,
[days_to_first_report_lifecycle] [numeric] (13, 2) NULL,
[inverted_days_to_first_report_lifecycle] [int] NULL,
[Suspicion of Fraud?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[tskDue] [datetime] NULL,
[tskCompleted] [datetime] NULL,
[tskDesc] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[File Opening SLA (days)] [float] NULL,
[File Opening SLA hidden on report for highlighting] [float] NOT NULL,
[Initial Report SLA (days)] [float] NULL,
[Initial Report SLA hidden on report for highlighting] [float] NOT NULL,
[Update Report SLA] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Update Report SLA (working days)] [float] NULL,
[Update Report SLA hidden on report for highlighting] [float] NOT NULL,
[File Opening RAG] [varchar] (11) COLLATE Latin1_General_CI_AS NOT NULL,
[nhs_sla_instruction_type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[NEW Initial Report RAG] [varchar] (11) COLLATE Latin1_General_CI_AS NULL,
[Inverted Initial Report RAG] [varchar] (11) COLLATE Latin1_General_CI_AS NULL,
[RagWithouthSub] [varchar] (11) COLLATE Latin1_General_CI_AS NOT NULL,
[referral_reason] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[delegated] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Count Initial Report Due In 5 Working Days] [int] NOT NULL,
[Count Initial Report Is Overdue] [int] NOT NULL,
[Date Subsequent Report Due] [datetime] NULL,
[Subsequent Report Due in 10 Working Days] [int] NOT NULL,
[Subsequent Report is Overdue] [int] NOT NULL,
[work_type_name] [char] (40) COLLATE Latin1_General_BIN NULL,
[nhsr_only_can_sub_report_rule_be_calculated] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
