CREATE TABLE [dbo].[AXAXLDataSubmission_Export_Create]
(
[Status] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[ms_fileid] [bigint] NULL,
[AXA XL Claim Number] [nvarchar] (2000) COLLATE Latin1_General_CI_AS NULL,
[Law Firm Matter Number] [nvarchar] (33) COLLATE Latin1_General_BIN NULL,
[Line of Business] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[New Line of Business] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Product Type] [char] (40) COLLATE Latin1_General_BIN NULL,
[Product Type New] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insured Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[AXA XL Percentage line share of loss / expenses / recovery] [money] NULL,
[AXA XL Claims Handler] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Third Party Administrator] [nvarchar] (80) COLLATE Latin1_General_CI_AS NULL,
[Coverage / defence?] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Law firm handling office (city)] [char] (40) COLLATE Latin1_General_BIN NULL,
[Date Instructed] [datetime] NULL,
[Opposing Side's Solicitor Firm Name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Reason For instruction] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Fee Scale] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Damages Claimed] [numeric] (13, 2) NULL,
[First acknowledgement Date] [datetime] NULL,
[Report Date] [datetime] NULL,
[Date Proceedings Issued] [datetime] NULL,
[AXA XL as defendant] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Reason for proceedings] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Proceeding Track] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Trial date] [datetime] NULL,
[Damages Reserve] [numeric] (13, 2) NULL,
[Opposing side's costs reserve] [numeric] (13, 2) NULL,
[Panel budget/reserve] [numeric] (13, 2) NULL,
[Reason for panel budget change if occurred] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Panel Fees Paid] [numeric] (13, 2) NULL,
[Counsel Paid] [numeric] (38, 5) NULL,
[Other Disbursements Paid] [numeric] (38, 5) NULL,
[Opposing side's Costs Claimed] [numeric] (13, 2) NULL,
[Timekeepers - Details of anyone who worked on the case during the time period.] [int] NULL,
[Name] [nvarchar] (102) COLLATE Latin1_General_BIN NULL,
[Timekeepers_Firstname] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Timekeepers_Lastname] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Unique timekeeper ID per timekeeper] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Level (solicitor, partner)] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[PQE] [int] NULL,
[Hours spent on case] [decimal] (38, 6) NULL,
[Upon closing a case add the following information] [int] NULL,
[Date closed] [date] NULL,
[Date of Final Panel Invoice] [datetime] NULL,
[Date Damages settled] [datetime] NULL,
[Final Damages Amount] [numeric] (13, 2) NULL,
[Claimants Costs Handled by Panel?] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Date Claimants costs settled] [datetime] NULL,
[Final Claimants Costs Amount] [numeric] (13, 2) NULL,
[Mediated outcome - Select from list] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Outcome of Instruction - Select from list] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Was litigation avoidable - Select from list] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[hierarchylevel3hist] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Weightmans Handler name] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[Referral reason] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[proceedings_issued] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Counsel Paid / Other disbursements] [numeric] (38, 5) NULL,
[Disbursements] [numeric] (38, 5) NULL,
[status_present_postition] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[date_closed_case_management] [datetime] NULL,
[matter_description] [varchar] (200) COLLATE Latin1_General_BIN NULL,
[insuredbroker_name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[broker_name] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[disbursements_billed] [numeric] (13, 2) NULL,
[Quantified Damages] [money] NULL,
[PanelFeesTest] [numeric] (38, 2) NULL,
[final_bill_flag] [char] (1) COLLATE Latin1_General_BIN NULL,
[RN] [bigint] NULL
) ON [PRIMARY]
GO
