CREATE TABLE [dbo].[RMLease25100kAllRecords]
(
[client] [char] (8) COLLATE Latin1_General_CI_AS NULL,
[matter] [char] (8) COLLATE Latin1_General_CI_AS NULL,
[case_id] [int] NOT NULL,
[TitleNumber] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[Demisedpremises] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Date] [date] NULL,
[Originallandlord] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Originaltenant] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[OriginalGuarantor] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Term] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Originalrent] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Nextreviewdate] [date] NULL,
[Upwardsonly] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Basisofreview] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Repairobligation] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Assignment] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Underletting] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Usepermitted] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Otherusespermitted] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Servicechargepayable] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Insuranceeffectedby] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Landlordsbreakoption] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[ConditionsA] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[Tenantsbreakoption] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[ConditionsB] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[LTA1954] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[Otherrelevantleaseterms] [nvarchar] (max) COLLATE Latin1_General_CI_AS NOT NULL,
[PRO984] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO985] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO986] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO987] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO988] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO989] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO990] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[PRO746Text] [char] (60) COLLATE Latin1_General_CI_AS NULL,
[NewRentalValue] [decimal] (18, 2) NULL,
[Term Start Date] [date] NULL,
[Term End Date] [date] NULL
) ON [PRIMARY]
GO
