CREATE TABLE [dbo].[hastings_listing_table]
(
[Exposure Number] [int] NULL,
[Claim Reference] [nvarchar] (2000) COLLATE Latin1_General_BIN NULL,
[Instruction Type] [nvarchar] (60) COLLATE Latin1_General_BIN NULL,
[Hastings Handler] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Supplier Handler] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Supplier Reference] [nvarchar] (33) COLLATE Latin1_General_BIN NULL,
[Case Description - DELETE BEFORE SENDING] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Present Position - DELETED BEFORE SENDING] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Referral Reason - DELETE BEFORE SENDING] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[work_type_name] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Supplier Branch] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Claimant First Name] [nvarchar] (max) COLLATE Latin1_General_BIN NULL,
[Claimant Surname] [nvarchar] (max) COLLATE Latin1_General_BIN NULL,
[Claimant Postcode] [nvarchar] (max) COLLATE Latin1_General_BIN NULL,
[Adult or Minor] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Male or Female] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[Injury Type] [nvarchar] (max) COLLATE Latin1_General_BIN NULL,
[Firm Injury Type - DELETE BEFORE SENDING] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Policyholder First Name] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Policyholder Last Name] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Policyholder Postcode] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Indemnity Position] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Date of Accident] [date] NULL,
[Date of Instruction] [date] NULL,
[Date Full File Received] [date] NULL,
[Accident Type] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Jurisdiction] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Fault Rating] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Fault Liability %] [nvarchar] (20) COLLATE Latin1_General_BIN NULL,
[Claimant Solicitor Firm] [nvarchar] (2000) COLLATE Latin1_General_BIN NULL,
[Claimant Solicitor Handler] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Claimant Solicitor Branch] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Fundamental Dishonesty] [nvarchar] (1) COLLATE Latin1_General_BIN NULL,
[hastings_fundamental_dishonesty] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Litigated] [nvarchar] (1) COLLATE Latin1_General_BIN NULL,
[Date Litigated] [date] NULL,
[Claim Status] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Allocated Courts] [nvarchar] (max) COLLATE Latin1_General_BIN NULL,
[Was Litigation Avoidable?] [nvarchar] (1) COLLATE Latin1_General_BIN NULL,
[Reason for Litigation] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Recovery to be Made?] [numeric] (13, 2) NULL,
[Recovery from] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Current Damages Reserve - DELETE BEFORE SENDING] [numeric] (13, 2) NULL,
[Claimant Schedule of Loss Value] [numeric] (13, 2) NULL,
[PPO Claimed] [nvarchar] (1) COLLATE Latin1_General_BIN NULL,
[Provisional Damages Claimed] [nvarchar] (1) COLLATE Latin1_General_BIN NULL,
[Counter Schedule of Loss Value] [numeric] (13, 2) NULL,
[Settlement Achieved] [nvarchar] (1) COLLATE Latin1_General_BIN NULL,
[Total Settlement] [numeric] (14, 2) NULL,
[Date of Settlement] [date] NULL,
[Damages Settlement Saving (money)] [numeric] (15, 2) NULL,
[Damages Settlement Saving (percent)] [numeric] (31, 16) NULL,
[Claimant Costs Claimed] [numeric] (13, 2) NULL,
[Claimant Disbursements Claimed] [numeric] (13, 2) NULL,
[Claimant Costs Paid] [numeric] (13, 2) NULL,
[Claimant Disbursements Paid] [numeric] (13, 2) NULL,
[Date Costs Paid] [date] NULL,
[Date Costs Settled - DELETED BEFORE SENDING] [date] NULL,
[Total Costs Claimed - DELETE BEFORE SENDING] [numeric] (13, 2) NULL,
[total_costs_claimed_rag_status] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[Total Costs Paid - DELETE BEFORE SENDING] [numeric] (13, 2) NULL,
[total_costs_paid_rag_status] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[Total Costs Savings (money)] [numeric] (15, 2) NULL,
[Total Costs Savings (percent)] [numeric] (32, 17) NULL,
[Total Costs of Claim Presented] [numeric] (14, 2) NULL,
[Total Claim Costs Savings (money)] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Total Claim Costs Savings (percent)] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[defence_costs_billed] [numeric] (13, 2) NULL,
[disbursements_billed] [numeric] (13, 2) NULL,
[vat_billed] [numeric] (13, 2) NULL,
[Suppliers Billing to Date] [numeric] (13, 2) NULL,
[Date of Final Invoice] [date] NULL,
[Suppliers Billing Paid] [decimal] (38, 2) NULL,
[VAT on Suppliers Billing Paid] [decimal] (38, 2) NULL,
[Suppliers Disbursements Paid] [decimal] (38, 2) NULL,
[Total Claim Cost] [numeric] (15, 2) NULL,
[Total Claim Saving £] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Total Claim Saving (percent)] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[Date Supplier Closed File] [date] NULL,
[Lifecycle Accident - Litigation] [int] NULL,
[Lifecycle Accident - Settlement] [int] NULL,
[Lifecycle Accident - Panel File Closure] [int] NULL,
[Lifecycle Instruction - Damages Settlement] [int] NULL,
[Lifecycle Instruction - Panel File Closure] [int] NULL,
[Lifecycle Litigation - Damages Settlement] [int] NULL,
[Lifecycle Damages Settlement - Costs Settlement] [int] NULL,
[Lifecycle Costs Settlement - Panel File Closure] [int] NULL,
[Date Closed on Mattersphere - DELETE BEFORE SENDING] [date] NULL,
[Unbilled WIP - DELETE BEFORE SENDING] [numeric] (13, 2) NULL,
[Unbilled Disbs - DELETE BEFORE SENDING] [numeric] (13, 2) NULL,
[Unpaid Bill Balance - DELETE BEFORE SENDING] [numeric] (13, 2) NULL,
[Date of Trial] [date] NULL,
[Date of Trial Window] [date] NULL,
[Date of Mediation] [date] NULL,
[Date of Infant Approval Hearing] [date] NULL,
[Date of Disposal Hearing] [date] NULL,
[has_trial] [int] NOT NULL,
[Date Opened on MS] [date] NULL,
[Date Instructions Received] [date] NULL,
[Date Full File of Papers Received] [datetime] NULL,
[Initial Report Required?] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Extension for Initial Report Agreed] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Initial Report Due] [date] NULL,
[Date Initial Report Sent] [date] NULL,
[Number of Business Days to Initial Report Sent] [numeric] (13, 2) NULL,
[Date of Last SLA Report] [date] NULL,
[Date Defence Due - Key Date] [date] NULL,
[Date Defence Due - MI Field] [date] NULL,
[Date Defence Filed] [date] NULL,
[Suspicion of Fraud?] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Type of Settlement] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Stage of Settlement] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Outcome of Case] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Offers Made with Intention to Rely on at Trial?] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Target Settlement Date] [date] NULL,
[Is Indemnity an Issue?] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Contribution Proceedings Issued?] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Are we Pursuing a Recovery] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Recovery Concluded] [date] NULL,
[Amount Recovered] [numeric] (13, 2) NULL,
[Gross Damages Reserve Exceed £350,000?] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Does the Claimant have a PI Claim?] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[PREDICT Damages Meta-model Value] [money] NULL,
[PREDICT Recommended Damages Reserve (Current)] [numeric] (13, 2) NULL,
[Damages Paid 100%] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[PREDICT Claimant Costs Meta-model Value] [money] NULL,
[PREDICT Recommended Claimant Costs Reserve (Current)] [numeric] (13, 2) NULL,
[PREDICT Lifecycle Meta-model Value] [numeric] (13, 2) NULL,
[PREDICT Recommended Settlement Time] [numeric] (13, 2) NULL,
[Damages Lifecycle] [int] NULL,
[SLA.A1 Instructions Acknowledged] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A2 File Allocated] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A2 on Collaborate] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A2 Refs Sent to Policyholder] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A2 Initial Contact with Claimant Sols] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A3 Initial Report 10 Days] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A4 Defencese Submitted 7 Days] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A5 Court Directions Provided to Hastings 2 Days] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A6 Defence Submitted to Court] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A7 Compliance with Court Dates] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A8 Identified Other Parties] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A9 Urgent Developments Reported] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A9 Update Reports Submitted] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A10 Significant Developments Reported] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A11 Non-urgent Written Responses] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A12 Urgent Written Responses] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A12 Supplier Written Responses] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A13 Responded to Phone Calls 2 Days] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A14 Outcome Reports Submitted 2 days] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A15 Trials Referred to Large Loss] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A15 Trial Advice Directed to Hastings] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A15 Full Report Tactics 2 Weeks] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A16 Trial Dates Missed] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A17 Experts Reports Provided to Hastings] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A17 Experts Reports Agreed with Hastings] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A19 Accurate Reserves Held] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A20 Justified Complaints Made] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A20 Non-Justified Complaints Made] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[SLA.A21 Any Leakage Identified] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Date of Last Review] [date] NULL,
[KPI A.1 Initial Advice] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.2 Fundamental Dishonesty Pleaded] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.2 Fundamental Dishonesty Success - Withdrawn] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.2 Fundamental Dishonesty Success - Compromised] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.2 Fundamental Dishonesty Success - Failed] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.2 Contribution Proceedings] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.3 Indemnity Recoveries] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.4 Offers and Outcomes] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.5 Lifecycle] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.6 PREDICT] [nvarchar] (15) COLLATE Latin1_General_BIN NULL,
[KPI A.7 Internal Monthly Audits] [nvarchar] (15) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
