CREATE TABLE [dbo].[AIGShortFormData]
(
[Client] [char] (8) COLLATE Latin1_General_BIN NULL,
[Matter] [char] (8) COLLATE Latin1_General_BIN NULL,
[Case Description] [varchar] (200) COLLATE Latin1_General_BIN NULL,
[Fee Earner] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[AIG Reference] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Insurer Reference] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[Insured Client] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[NumberRefs] [int] NULL,
[AIG litigation number] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[AIG) Instructing office] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Client's claims handler] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Opened on FED] [datetime] NULL,
[Fixed Fee] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Suspicion of fraud?] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Initial fraud type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Current fraud type] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[AIG Current Fee Scale] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Referral Reason] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Present Position] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Outcome] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Date Claim Concluded] [datetime] NULL,
[Date Costs Settled] [datetime] NULL,
[Unpaid Bills] [numeric] (13, 2) NULL,
[UnSubmittedDebt] [numeric] (38, 2) NULL,
[SubmittedDebt] [numeric] (38, 2) NULL,
[Unpaid WIP] [numeric] (38, 2) NOT NULL,
[Total Billed to Date] [numeric] (38, 5) NULL,
[Defence Costs Reserve Current] [numeric] (13, 2) NULL,
[Net Defence Costs Reserve] [numeric] (38, 5) NULL,
[Evaluation fees - experts/consultants] [numeric] (13, 2) NULL,
[Evaluation fees - documents/file management] [numeric] (13, 2) NULL,
[Evaluation fees - budgeting] [numeric] (13, 2) NULL,
[Evaluation fees - pleadings] [numeric] (13, 2) NULL,
[Evaluation fees - prelim injunctions/provisional remedies] [numeric] (13, 2) NULL,
[Evaluation fees - fact investigation/development] [numeric] (13, 2) NULL,
[Evaluation fees - analysis/strategy] [numeric] (13, 2) NULL,
[Discovery/Disclosure fees - court mandated conferences] [numeric] (13, 2) NULL,
[Discovery/Disclosure fees-other written motion.submission] [numeric] (13, 2) NULL,
[Discovery/Disclosure fees-written discovery/interrogatori] [numeric] (13, 2) NULL,
[Discovery/Disclosure fees - document production] [numeric] (13, 2) NULL,
[Discovery/Disclosure fees - depositions] [numeric] (13, 2) NULL,
[Discovery/Disclosure fees - expert discovery] [numeric] (13, 2) NULL,
[Discovery/Disclosure fees - discovery motions] [numeric] (13, 2) NULL,
[Discovery/Disclosure fees - discovery on-site inspections] [numeric] (13, 2) NULL,
[ADR fees - Settlement.non-binding ADR] [numeric] (13, 2) NULL,
[Trial fees - fact witnesses] [numeric] (13, 2) NULL,
[Trial fees - expert witnesses] [numeric] (13, 2) NULL,
[Trial fees - written motions/submissions] [numeric] (13, 2) NULL,
[Trial fees - trial preparation + support] [numeric] (13, 2) NULL,
[Trial fees - trial and hearing attendance] [numeric] (13, 2) NULL,
[Trial fees - post trial motions/submissions] [numeric] (13, 2) NULL,
[Trial fees - enforcement] [numeric] (13, 2) NULL,
[Appeal fees - appellate proceedings/motions practice] [numeric] (13, 2) NULL,
[Appeal fees - appellate briefs] [numeric] (13, 2) NULL,
[Appeal fees - oral argument] [numeric] (13, 2) NULL,
[Overall costs budget figure] [numeric] (13, 2) NULL,
[Evaluation expenses] [numeric] (13, 2) NULL,
[Discovery/Disclosure expenses] [numeric] (13, 2) NULL,
[ADR expenses] [numeric] (13, 2) NULL,
[Trial expenses] [numeric] (13, 2) NULL,
[Appeal expenses] [numeric] (13, 2) NULL,
[Multi-Phase expenses] [numeric] (13, 2) NULL,
[Overall expenses figure] [numeric] (13, 2) NULL,
[Fixed Fee Budget - Fees] [numeric] (13, 2) NULL,
[Fixed Fee Budget - Expenses] [numeric] (13, 2) NULL,
[Fixed Fee Budget - Vat] [numeric] (13, 2) NULL,
[AIGHIDE_Flag] [int] NOT NULL,
[Date instructions received] [datetime] NULL,
[AIG Budget approval] [char] (60) COLLATE Latin1_General_BIN NULL,
[Total budget uploaded] [numeric] (13, 2) NOT NULL,
[Total] [numeric] (14, 2) NULL,
[Date budget uploaded] [datetime] NULL,
[First Budget uploaded] [datetime] NULL,
[Has budget been approved?] [char] (60) COLLATE Latin1_General_BIN NULL,
[Percentage Of Budget] [decimal] (38, 6) NULL,
[LeadLinkedTotalBilled] [numeric] (38, 5) NOT NULL,
[LeadLinkedFixedFee] [numeric] (38, 2) NOT NULL,
[LeadLinkedWIP] [numeric] (38, 2) NOT NULL,
[LeadLinkedDis] [numeric] (38, 2) NOT NULL,
[Is Insured VAT Registered] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Master Client] [nvarchar] (12) COLLATE Latin1_General_BIN NULL,
[Master Matter] [nvarchar] (20) COLLATE Latin1_General_BIN NULL,
[Exceptions] [varchar] (266) COLLATE Latin1_General_CI_AS NOT NULL,
[BudgetNotMatch] [int] NULL,
[UnbilledDisbs] [numeric] (13, 2) NOT NULL,
[Is this a linked file] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Is this the lead file] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Lead file matter number] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[Fedcode] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Total Billed To Date Lead Linked] [numeric] (38, 5) NULL,
[LeadlinkedTRA078] [numeric] (38, 2) NULL,
[LeadFileBudget] [varchar] (3) COLLATE Latin1_General_CI_AS NOT NULL,
[AIGTotalBudgetFixedFee] [numeric] (13, 2) NULL,
[AIGTotalBudgetHourlyRate] [numeric] (13, 2) NULL,
[LIT216] [numeric] (13, 2) NULL,
[TotalBudgetRemaining] [numeric] (38, 5) NULL,
[TotalBudgetRemainingVAt] [numeric] (38, 5) NULL,
[FED Ref] [varchar] (8000) COLLATE Latin1_General_BIN NULL,
[MS Ref] [nvarchar] (4000) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
