CREATE TABLE [dbo].[AXAXLDataSubmissionAPIStage]
(
[Status] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AXA XL Claim Number] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[F3] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Law Firm Matter Number] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Line of Business] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Product Type] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Insured Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AXA XL Percentage line share of loss expenses recovery] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AXA XL Claims Handler] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Third Party Administrator] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Coverage defence ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Law firm handling office city ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Instructed] [datetime] NULL,
[Opposing Side's Solicitor Firm Name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Reason For instruction] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Fee Scale] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Damages Claimed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[First acknowledgement Date] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Report Date] [datetime] NULL,
[Date Proceedings Issued] [datetime] NULL,
[AXA XL as defendant] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Reason for proceedings] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Proceeding Track] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Trial date] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Damages Reserve] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Opposing sides costs reserve] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Panel budget reserve] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Reason for panel budget change if occurred] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Panel Fees Paid] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Counsel Paid] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Other Disbursements Paid] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Opposing sides Costs Claimed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[First_name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Last_name] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Unique timekeeper ID per timekeeper] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Level solicitor partner ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PQE] [float] NULL,
[F38] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Hours spent on case] [money] NULL,
[Date closed] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date of Final Panel Invoice] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Damages settled] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Final Damages Amount] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Claimants Costs Handled by Panel ] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Date Claimants costs settled] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Final Claimants Costs Amount] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Mediated outcome Select from list] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Outcome of Instruction Select from list] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Was litigation avoidable Select from list] [nvarchar] (255) COLLATE Latin1_General_CI_AS NULL,
[dss_load_date] [datetime] NULL,
[dss_current_flag] [char] (1) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
