CREATE TABLE [dbo].[ccpx1]
(
[Customer] [int] NOT NULL,
[Demand] [int] NULL,
[1] [int] NULL,
[2] [int] NULL,
[3] [int] NULL,
[4] [int] NULL,
[5] [int] NULL,
[6] [int] NULL,
[7] [int] NULL,
[8] [int] NULL,
[9] [int] NULL,
[10] [int] NULL,
[11] [int] NULL,
[12] [int] NULL,
[13] [int] NULL,
[14] [int] NULL,
[15] [int] NULL,
[16] [int] NULL,
[17] [int] NULL,
[18] [int] NULL,
[19] [int] NULL,
[20] [int] NULL,
[21] [int] NULL,
[22] [int] NULL,
[23] [int] NULL,
[24] [int] NULL,
[25] [int] NULL,
[26] [int] NULL,
[27] [int] NULL,
[28] [int] NULL,
[29] [int] NULL,
[30] [int] NULL,
[31] [int] NULL,
[32] [int] NULL,
[33] [int] NULL,
[34] [int] NULL,
[35] [int] NULL,
[36] [int] NULL,
[37] [int] NULL,
[38] [int] NULL,
[39] [int] NULL,
[40] [int] NULL,
[41] [int] NULL,
[42] [int] NULL,
[43] [int] NULL,
[44] [int] NULL,
[45] [int] NULL,
[46] [int] NULL,
[47] [int] NULL,
[48] [int] NULL,
[49] [int] NULL,
[50] [int] NULL,
[selected] [int] NULL,
[selectedphase] [int] NULL,
[selected1] [int] NULL,
[selected2] [int] NULL,
[selected3] [int] NULL,
[selected4] [int] NULL,
[selected5] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ccpx1] ADD CONSTRAINT [PK_ccpx1] PRIMARY KEY CLUSTERED  ([Customer]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx51] ON [dbo].[ccpx1] ([Demand]) ON [PRIMARY]
GO
