CREATE TABLE [dbo].[ClaimsManagementReportSnapshotTable]
(
[employeeid] [char] (36) COLLATE Latin1_General_BIN NULL,
[Name] [nvarchar] (100) COLLATE Latin1_General_BIN NULL,
[Division] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Department] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Team] [nvarchar] (50) COLLATE Latin1_General_BIN NULL,
[Contractual hours per day] [numeric] (18, 2) NULL,
[Annual Holiday Allowance] [numeric] (25, 2) NULL,
[Annual Working Days] [int] NULL,
[Holidays Taken to Date] [numeric] (38, 2) NULL,
[Holidays yet to Take] [numeric] (38, 2) NULL,
[Working Days to Date] [numeric] (29, 16) NULL,
[Chargeable Hours] [numeric] (38, 6) NULL,
[AVGChargeableHours] [numeric] (38, 6) NULL,
[ChargeableHoursMTD] [numeric] (38, 6) NULL,
[Utilisation %] [numeric] (38, 6) NULL,
[SicknessDays] [numeric] (38, 2) NULL,
[OtherDays] [numeric] (38, 2) NULL,
[MonthlyContribution] [float] NULL,
[YTDContribution] [float] NULL,
[Chargeable hours target] [numeric] (38, 2) NULL,
[Revenue target] [numeric] (38, 2) NULL,
[YTDTargetHrs] [numeric] (38, 2) NULL,
[YTDTargetRevenue] [numeric] (38, 2) NULL,
[Chargeable hours target Annual] [numeric] (38, 2) NULL,
[Revenue target Annual] [numeric] (38, 2) NULL,
[FinMonth] [int] NULL,
[FinYear] [int] NULL,
[Period] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[fed_code] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
