IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SBC\DEV-WEBAPP-OneToOne')
CREATE LOGIN [SBC\DEV-WEBAPP-OneToOne] FROM WINDOWS
GO
CREATE USER [SBC\DEV-WEBAPP-OneToOne] FOR LOGIN [SBC\DEV-WEBAPP-OneToOne]
GO
