IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SBC\SQL ROLE - IS_WEB_DEVELOPER')
CREATE LOGIN [SBC\SQL ROLE - IS_WEB_DEVELOPER] FROM WINDOWS
GO
CREATE USER [SBC\SQL ROLE - IS_WEB_DEVELOPER] FOR LOGIN [SBC\SQL ROLE - IS_WEB_DEVELOPER]
GO
