IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SBC\UAT-WEBAPP- OneToOne')
CREATE LOGIN [SBC\UAT-WEBAPP- OneToOne] FROM WINDOWS
GO
CREATE USER [SBC\UAT-WEBAPP- OneToOne] FOR LOGIN [SBC\UAT-WEBAPP- OneToOne]
GO
